-- MedLevo AI — core schema (SQLite, STRICT tables).
-- Conventions
--   * ids: TEXT ULIDs (time-sortable, generated by server or client for sync-safe entities)
--   * time: INTEGER epoch milliseconds, UTC. Display timezone is an owner setting.
--   * json columns end with _json and hold validated JSON (zod schemas in @medlevo/shared)
--   * soft delete: deleted_at (trash). Permanent delete is an explicit, separate action.
--   * The relational DB is the source of truth for identity, versions, relations and status.
--     The FTS index and any embeddings are derived and can be rebuilt.
-- Single owner: there are no organizations, roles, cohorts, subscriptions or multi-tenancy.

PRAGMA foreign_keys = ON;

-- ───────────────────────────── Owner & auth ─────────────────────────────
CREATE TABLE owner (
  id TEXT PRIMARY KEY CHECK (id = 'owner'),          -- exactly one owner row can exist
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,                       -- scrypt$N$r$p$salt$hash
  recovery_codes_json TEXT NOT NULL DEFAULT '[]',    -- array of scrypt hashes; used codes removed
  password_changed_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_session (
  id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,                   -- sha256 of the opaque cookie token
  device_id TEXT,                                    -- client device id (for sync attribution)
  device_label TEXT,
  user_agent TEXT,
  ip TEXT,
  created_at INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  revoked_at INTEGER
) STRICT;

CREATE TABLE login_attempt (
  id TEXT PRIMARY KEY,
  ip TEXT,
  succeeded INTEGER NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_login_attempt_time ON login_attempt(created_at);

-- Personal settings (key/value; values validated per key in shared/settings.ts)
CREATE TABLE owner_setting (
  key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

-- Audit / change log for owner-visible history (not a debug log)
CREATE TABLE change_log (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,                              -- create|update|move|rename|trash|restore|purge|correct|review|...
  summary TEXT,
  before_json TEXT,
  after_json TEXT,
  actor TEXT NOT NULL DEFAULT 'owner',               -- owner|system|job
  job_id TEXT,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_change_log_entity ON change_log(entity_type, entity_id, created_at);

-- ───────────────────────────── Library ─────────────────────────────
-- One tree for personal organization. kinds are personal study data, NOT institutions.
CREATE TABLE library_node (
  id TEXT PRIMARY KEY,
  parent_id TEXT REFERENCES library_node(id),
  kind TEXT NOT NULL CHECK (kind IN ('notebook','folder','subject','course','section','topic_folder')),
  title TEXT NOT NULL,
  description TEXT,
  color TEXT,                                        -- token name, e.g. 'teal' (not raw hex)
  icon TEXT,                                         -- icon token name
  cover_json TEXT,                                   -- {style:'plain'|'linen'|'pattern', color, emoji?}
  template TEXT,                                     -- optional study template key (anatomy, pharmacology, ...)
  sort_order REAL NOT NULL DEFAULT 0,                -- manual ordering (fractional indexing)
  sort_mode TEXT NOT NULL DEFAULT 'manual' CHECK (sort_mode IN ('manual','title','updated','created')),
  is_favorite INTEGER NOT NULL DEFAULT 0,
  archived_at INTEGER,
  deleted_at INTEGER,                                -- in trash
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_library_node_parent ON library_node(parent_id, sort_order);

CREATE TABLE tag (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE COLLATE NOCASE,
  color TEXT,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE tag_link (
  tag_id TEXT NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,                         -- library_node|source|question|flashcard|note
  entity_id TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (tag_id, entity_type, entity_id)
) STRICT;
CREATE INDEX idx_tag_link_entity ON tag_link(entity_type, entity_id);

-- ───────────────────────────── Files ─────────────────────────────
-- Content-addressed private blobs. Never served from a public path.
CREATE TABLE stored_file (
  id TEXT PRIMARY KEY,
  sha256 TEXT NOT NULL UNIQUE,
  size INTEGER NOT NULL,
  mime TEXT NOT NULL,
  storage_key TEXT NOT NULL,                         -- relative path under DATA_DIR/files
  original_name TEXT,
  created_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Sources ─────────────────────────────
CREATE TABLE source (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  source_type TEXT NOT NULL CHECK (source_type IN (
    'lecture','course_reference','textbook','guideline','question_source','previous_exam',
    'image_atlas','practical_manual','my_notes','lecture_audio','my_audio_note','external_source')),
  language TEXT,                                     -- 'ar'|'en'|'mixed'|null (unknown)
  node_id TEXT REFERENCES library_node(id),          -- primary folder placement
  subject_node_id TEXT REFERENCES library_node(id),
  course_node_id TEXT REFERENCES library_node(id),
  lecture_kind TEXT CHECK (lecture_kind IN ('theoretical','practical','clinical','mixed')),
  lecture_kind_origin TEXT CHECK (lecture_kind_origin IN ('auto','owner')),
  -- bibliographic metadata: only what the file/owner actually provides. Never invented.
  edition TEXT,
  authors_json TEXT,
  publication_date TEXT,
  original_url TEXT,
  metadata_status TEXT NOT NULL DEFAULT 'unknown' CHECK (metadata_status IN ('unknown','partial','owner_confirmed')),
  -- suitability for tasks (separate from extraction accuracy)
  priority INTEGER NOT NULL DEFAULT 0,
  selection_reason TEXT,
  processing_status TEXT NOT NULL DEFAULT 'pending' CHECK (processing_status IN (
    'pending','processing','partial','ready','failed','needs_review')),
  current_version_id TEXT,                           -- latest version
  frozen_version_id TEXT,                            -- Source Freeze: pinned version for study
  sort_order REAL NOT NULL DEFAULT 0,
  is_favorite INTEGER NOT NULL DEFAULT 0,
  last_opened_at INTEGER,
  archived_at INTEGER,
  deleted_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_source_node ON source(node_id);
CREATE INDEX idx_source_course ON source(course_node_id);

-- Explicit relations between sources: a lecture's selected references, a question source for a course, ...
CREATE TABLE source_link (
  id TEXT PRIMARY KEY,
  from_source_id TEXT NOT NULL REFERENCES source(id),
  to_source_id TEXT NOT NULL REFERENCES source(id),
  relation TEXT NOT NULL CHECK (relation IN ('reference_for','question_source_for','audio_for','same_topic')),
  created_at INTEGER NOT NULL,
  UNIQUE (from_source_id, to_source_id, relation)
) STRICT;

-- A specific, traceable version. The original file is never modified;
-- corrections / OCR / conversions are derived versions.
CREATE TABLE source_version (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL REFERENCES source(id),
  version_no INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('original','converted','ocr_correction','owner_correction','replacement')),
  derived_from_version_id TEXT REFERENCES source_version(id),
  file_id TEXT REFERENCES stored_file(id),           -- the file this version renders from
  original_file_id TEXT REFERENCES stored_file(id),  -- the uploaded original (e.g. .doc before conversion)
  content_hash TEXT NOT NULL,
  mime TEXT NOT NULL,
  file_name TEXT,
  format TEXT NOT NULL CHECK (format IN ('pdf','docx','pptx','image','image_set','audio','text')),
  page_count INTEGER,
  pagination TEXT NOT NULL DEFAULT 'pages' CHECK (pagination IN ('pages','slides','paragraphs','images','timestamps')),
  processing_status TEXT NOT NULL DEFAULT 'pending' CHECK (processing_status IN (
    'pending','processing','partial','ready','failed','needs_review')),
  processing_summary_json TEXT,                      -- counts per stage, failed pages, coverage
  note TEXT,
  created_at INTEGER NOT NULL,
  UNIQUE (source_id, version_no)
) STRICT;
CREATE INDEX idx_source_version_source ON source_version(source_id);

-- A page / slide / image / docx section in a version.
-- page_index is the 0-based order inside the file; printed_label is what is printed on the page.
CREATE TABLE source_page (
  id TEXT PRIMARY KEY,
  version_id TEXT NOT NULL REFERENCES source_version(id),
  page_index INTEGER NOT NULL,
  printed_label TEXT,
  printed_label_origin TEXT CHECK (printed_label_origin IN ('pdf_page_labels','detected_text','owner','slide_number')),
  kind TEXT NOT NULL DEFAULT 'page' CHECK (kind IN ('page','slide','image','docx_section','audio_segment')),
  width REAL,                                        -- page size in its native unit (PDF points / px)
  height REAL,
  unit TEXT CHECK (unit IN ('pt','px')),
  rotation INTEGER NOT NULL DEFAULT 0,               -- intrinsic /Rotate of the page, degrees
  text_status TEXT NOT NULL DEFAULT 'pending' CHECK (text_status IN (
    'pending','digital','ocr','mixed','no_text_found','needs_ocr','failed')),
  ocr_confidence REAL,
  has_images INTEGER NOT NULL DEFAULT 0,
  processing_status TEXT NOT NULL DEFAULT 'pending' CHECK (processing_status IN (
    'pending','processing','ready','failed','needs_review','skipped')),
  error_code TEXT,
  error_detail TEXT,
  thumbnail_file_id TEXT REFERENCES stored_file(id),
  render_file_id TEXT REFERENCES stored_file(id),    -- raster used for OCR / image sources
  section_key TEXT,                                  -- e.g. question section, docx heading path
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (version_id, page_index)
) STRICT;

-- A region inside a page: text block, heading, table, figure, caption, question, option, key...
-- bbox_json is normalized to the UNROTATED page box: {x,y,w,h} in [0,1], origin top-left.
-- locator_json holds non-page locators (docx paragraph index, pptx shape id, audio {start_ms,end_ms}).
CREATE TABLE source_region (
  id TEXT PRIMARY KEY,
  version_id TEXT NOT NULL REFERENCES source_version(id),
  page_id TEXT REFERENCES source_page(id),
  parent_region_id TEXT REFERENCES source_region(id),
  kind TEXT NOT NULL CHECK (kind IN (
    'text_block','heading','paragraph','list_item','table','table_cell','figure','caption',
    'diagram','question','option','answer_key','transcript','note','footer','header')),
  reading_order INTEGER NOT NULL DEFAULT 0,
  bbox_json TEXT,
  locator_json TEXT,
  text TEXT,                                         -- logical-order text (no injected bidi marks)
  text_origin TEXT CHECK (text_origin IN ('digital','ocr','owner','vision')),
  lang TEXT,
  confidence REAL,                                   -- OCR / detection confidence when known
  structure_json TEXT,                               -- table cells {r,c,rowspan,colspan,header}, diagram {nodes,edges}
  status TEXT NOT NULL DEFAULT 'extracted' CHECK (status IN ('extracted','checks_passed','needs_review','uncertain','owner_reviewed','rejected')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_source_region_page ON source_region(page_id, reading_order);
CREATE INDEX idx_source_region_version ON source_region(version_id);

-- Retrieval units. A chunk is a paragraph / table / figure+caption, not a fixed char window.
CREATE TABLE document_chunk (
  id TEXT PRIMARY KEY,
  version_id TEXT NOT NULL REFERENCES source_version(id),
  source_id TEXT NOT NULL REFERENCES source(id),
  kind TEXT NOT NULL,                                -- text|table|figure|question|transcript|note
  heading_path TEXT,
  text TEXT NOT NULL,
  region_ids_json TEXT NOT NULL,                     -- regions that compose this chunk
  page_ids_json TEXT NOT NULL,
  prev_chunk_id TEXT,
  next_chunk_id TEXT,
  token_estimate INTEGER,
  index_version TEXT NOT NULL,                       -- chunking/index scheme version
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_chunk_version ON document_chunk(version_id);

CREATE VIRTUAL TABLE chunk_fts USING fts5(
  text, heading_path,
  content='document_chunk', content_rowid='rowid',
  tokenize = 'unicode61 remove_diacritics 2'
);
CREATE TRIGGER chunk_fts_ai AFTER INSERT ON document_chunk BEGIN
  INSERT INTO chunk_fts(rowid, text, heading_path) VALUES (new.rowid, new.text, new.heading_path);
END;
CREATE TRIGGER chunk_fts_ad AFTER DELETE ON document_chunk BEGIN
  INSERT INTO chunk_fts(chunk_fts, rowid, text, heading_path) VALUES ('delete', old.rowid, old.text, old.heading_path);
END;
CREATE TRIGGER chunk_fts_au AFTER UPDATE ON document_chunk BEGIN
  INSERT INTO chunk_fts(chunk_fts, rowid, text, heading_path) VALUES ('delete', old.rowid, old.text, old.heading_path);
  INSERT INTO chunk_fts(rowid, text, heading_path) VALUES (new.rowid, new.text, new.heading_path);
END;

-- Optional embeddings (only when an embeddings provider is configured). Derived, rebuildable.
CREATE TABLE chunk_embedding (
  chunk_id TEXT NOT NULL REFERENCES document_chunk(id) ON DELETE CASCADE,
  model TEXT NOT NULL,
  dims INTEGER NOT NULL,
  vector BLOB NOT NULL,                              -- Float32Array bytes
  created_at INTEGER NOT NULL,
  PRIMARY KEY (chunk_id, model)
) STRICT;

-- ───────────────────────────── Knowledge & evidence ─────────────────────────────
CREATE TABLE topic (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  title_ar TEXT,
  parent_topic_id TEXT REFERENCES topic(id),
  concept_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

-- topic ↔ anything (source, region, question, flashcard...). Auto suggestions are correctable.
CREATE TABLE topic_link (
  id TEXT PRIMARY KEY,
  topic_id TEXT NOT NULL REFERENCES topic(id),
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  origin TEXT NOT NULL CHECK (origin IN ('auto','owner')),
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','accepted','rejected')),
  created_at INTEGER NOT NULL,
  UNIQUE (topic_id, entity_type, entity_id)
) STRICT;

CREATE TABLE concept (
  id TEXT PRIMARY KEY,
  name_en TEXT,
  name_ar TEXT,
  kind TEXT,                                         -- disease|structure|drug|mechanism|investigation|sign|...
  definition_claim_id TEXT,
  origin TEXT NOT NULL DEFAULT 'auto' CHECK (origin IN ('auto','owner')),
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','accepted','rejected')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE concept_relation (
  id TEXT PRIMARY KEY,
  from_concept_id TEXT NOT NULL REFERENCES concept(id),
  to_concept_id TEXT NOT NULL REFERENCES concept(id),
  relation TEXT NOT NULL,                            -- prerequisite|part_of|differential_of|causes|treats|related
  support TEXT NOT NULL CHECK (support IN ('stated','inferred')),
  evidence_ids_json TEXT,
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','accepted','rejected')),
  created_at INTEGER NOT NULL
) STRICT;

-- concept occurrences in source regions (Course Brain)
CREATE TABLE concept_mention (
  id TEXT PRIMARY KEY,
  concept_id TEXT NOT NULL REFERENCES concept(id),
  region_id TEXT NOT NULL REFERENCES source_region(id),
  version_id TEXT NOT NULL REFERENCES source_version(id),
  role TEXT,                                         -- definition|mechanism|feature|investigation|management|...
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_concept_mention_concept ON concept_mention(concept_id);

CREATE TABLE medical_term (
  id TEXT PRIMARY KEY,
  term_en TEXT NOT NULL,
  abbreviation TEXT,
  synonyms_json TEXT NOT NULL DEFAULT '[]',
  explanation_ar TEXT,
  accepted_translation_ar TEXT,
  owner_preferred_ar TEXT,                           -- owner correction; never edits source text
  origin TEXT NOT NULL DEFAULT 'owner' CHECK (origin IN ('owner','extracted','generated')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE UNIQUE INDEX idx_medical_term_en ON medical_term(term_en COLLATE NOCASE);

-- An exact excerpt of a specific region in a specific version. The only thing a citation can point to.
CREATE TABLE evidence (
  id TEXT PRIMARY KEY,
  version_id TEXT NOT NULL REFERENCES source_version(id),
  source_id TEXT NOT NULL REFERENCES source(id),
  page_id TEXT REFERENCES source_page(id),
  region_id TEXT REFERENCES source_region(id),
  quote TEXT NOT NULL,                               -- verbatim excerpt (logical order)
  start_offset INTEGER,                              -- offsets into region.text when applicable
  end_offset INTEGER,
  bbox_json TEXT,                                    -- optional sub-region box (normalized)
  created_at INTEGER NOT NULL,
  UNIQUE (region_id, start_offset, end_offset)
) STRICT;

-- Generated / owner artifacts: study book, summaries, explanations, chat answers, comparisons, maps.
-- lineage_id is stable across versions; (lineage_id, version_no) identifies a version.
CREATE TABLE artifact (
  id TEXT PRIMARY KEY,
  lineage_id TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('study_book','summary','explanation','chat_answer','comparison','mind_map','flowchart','figure_explanation','case_explanation')),
  title TEXT,
  primary_source_id TEXT REFERENCES source(id),
  scope_json TEXT NOT NULL,                          -- SourceScope (mode + allowed source/version ids)
  params_json TEXT NOT NULL,                         -- level, language, dialect, summary type, custom instructions
  cache_key TEXT NOT NULL,                           -- hash of everything that affects output (see ARCHITECTURE)
  rules_version TEXT NOT NULL,
  generator_version TEXT NOT NULL,
  verifier_version TEXT NOT NULL,
  model TEXT,                                        -- actual model used (null for deterministic)
  status TEXT NOT NULL CHECK (status IN ('draft','generating','partial','verifying','published','stale','failed','superseded')),
  coverage_json TEXT,                                -- pages/sections/concepts processed vs total
  job_id TEXT,
  is_frozen INTEGER NOT NULL DEFAULT 0,
  stale_reason TEXT,
  created_at INTEGER NOT NULL,
  published_at INTEGER,
  updated_at INTEGER NOT NULL,
  UNIQUE (lineage_id, version_no)
) STRICT;
CREATE INDEX idx_artifact_cache ON artifact(cache_key);
CREATE INDEX idx_artifact_source ON artifact(primary_source_id, kind);

-- Structured content blocks of an artifact. block_key is stable across versions (semantic anchors).
CREATE TABLE content_block (
  id TEXT PRIMARY KEY,
  artifact_id TEXT NOT NULL REFERENCES artifact(id),
  block_key TEXT NOT NULL,
  section_key TEXT,
  ord INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN (
    'heading','paragraph','term','figure','comparison_table','clinical_note','exam_pearl','mini_question',
    'memory_hook','example','original_quote','list','flowchart','warning','coverage_note')),
  content_json TEXT NOT NULL,                        -- RichText: runs with lang/dir; see shared/richtext.ts
  source_region_ids_json TEXT NOT NULL DEFAULT '[]', -- original regions this block explains
  status TEXT NOT NULL DEFAULT 'complete' CHECK (status IN ('complete','incomplete','rejected')),
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','linked','needs_review','conflict','rejected','owner_reviewed','not_applicable')),
  created_at INTEGER NOT NULL,
  UNIQUE (artifact_id, block_key)
) STRICT;
CREATE INDEX idx_content_block_artifact ON content_block(artifact_id, ord);

-- A medical claim made inside an artifact / question / card / message.
CREATE TABLE claim (
  id TEXT PRIMARY KEY,
  owner_type TEXT NOT NULL,                          -- content_block|question_version|flashcard|message|case
  owner_id TEXT NOT NULL,
  text TEXT NOT NULL,
  lang TEXT,
  support_type TEXT NOT NULL CHECK (support_type IN (
    'directly_stated','derived','synthesized','externally_supplemented','contradicted','unsupported')),
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN (
    'pending','linked','needs_review','conflict','rejected','owner_reviewed')),
  critical_flags_json TEXT,                          -- negation/number/unit/dose/threshold/age/exception present
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_claim_owner ON claim(owner_type, owner_id);

CREATE TABLE citation (
  id TEXT PRIMARY KEY,
  claim_id TEXT NOT NULL REFERENCES claim(id) ON DELETE CASCADE,
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  relation TEXT NOT NULL CHECK (relation IN ('supports','partially_supports','contradicts','context')),
  created_at INTEGER NOT NULL,
  UNIQUE (claim_id, evidence_id)
) STRICT;
CREATE INDEX idx_citation_evidence ON citation(evidence_id);

CREATE TABLE verification_result (
  id TEXT PRIMARY KEY,
  subject_type TEXT NOT NULL,                        -- claim|question_version|artifact|region|...
  subject_id TEXT NOT NULL,
  check_name TEXT NOT NULL,                          -- schema|evidence_exists|scope|critical_tokens|entailment|single_best_answer|...
  passed INTEGER NOT NULL,
  details_json TEXT,
  verifier TEXT NOT NULL,                            -- 'deterministic' or provider:model
  verifier_version TEXT NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_verification_subject ON verification_result(subject_type, subject_id);

-- What every derived thing depends on, for change alerts and staleness.
CREATE TABLE artifact_dependency (
  id TEXT PRIMARY KEY,
  dependent_type TEXT NOT NULL,                      -- artifact|question_version|flashcard|exam
  dependent_id TEXT NOT NULL,
  source_version_id TEXT NOT NULL REFERENCES source_version(id),
  region_id TEXT,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_artifact_dep_version ON artifact_dependency(source_version_id);
CREATE INDEX idx_artifact_dep_dependent ON artifact_dependency(dependent_type, dependent_id);

CREATE TABLE content_alert (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('source_updated','ocr_corrected','key_corrected','source_deleted','source_replaced','conflict_found','layout_changed')),
  severity TEXT NOT NULL CHECK (severity IN ('info','fact_change','answer_change')),
  source_id TEXT,
  source_version_id TEXT,
  summary TEXT NOT NULL,
  affected_json TEXT NOT NULL,                       -- [{type,id,impact:'still_valid'|'needs_regeneration'|'needs_review'}]
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','resolved')),
  created_at INTEGER NOT NULL,
  resolved_at INTEGER
) STRICT;

-- ───────────────────────────── Notes, ink, anchors ─────────────────────────────
-- Paper pages created by the owner (blank/ruled/dotted/grid), inside a notebook/folder or after a source page.
CREATE TABLE note_page (
  id TEXT PRIMARY KEY,
  node_id TEXT REFERENCES library_node(id),
  source_id TEXT REFERENCES source(id),
  after_page_index INTEGER,
  title TEXT,
  template TEXT NOT NULL DEFAULT 'blank' CHECK (template IN ('blank','ruled','dotted','grid')),
  width REAL NOT NULL DEFAULT 595,
  height REAL NOT NULL DEFAULT 842,
  sort_order REAL NOT NULL DEFAULT 0,
  deleted_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

-- One row per ink stroke / highlight / shape / sticky / text box / bookmark.
-- Strokes are append-only with tombstones (deleted_at) so multi-device merge never loses writing.
-- anchor_json:
--   page anchor     {type:'page', version_id, page_id, page_index, space:'page_norm'}  (coords normalized to unrotated page)
--   note page       {type:'note_page', note_page_id, space:'page_norm'}
--   semantic anchor {type:'block', lineage_id, artifact_version, block_key, quote:{exact,prefix,suffix}, start, end}
CREATE TABLE annotation (
  id TEXT PRIMARY KEY,                               -- client-generated ULID (idempotent sync)
  kind TEXT NOT NULL CHECK (kind IN ('ink','highlight','underline','shape','text','sticky','image','bookmark','link','text_highlight')),
  tool TEXT,                                         -- pen|fountain|ball|highlighter|line|arrow|rect|ellipse|...
  anchor_json TEXT NOT NULL,
  data_json TEXT NOT NULL,                           -- points [[x,y,t,pressure?,tiltX?,tiltY?],...], style, text, ...
  layer TEXT NOT NULL DEFAULT 'ink' CHECK (layer IN ('ink','highlight','text','media')),
  z INTEGER NOT NULL DEFAULT 0,
  locked INTEGER NOT NULL DEFAULT 0,
  anchor_status TEXT NOT NULL DEFAULT 'ok' CHECK (anchor_status IN ('ok','needs_reanchor','reanchored')),
  previous_anchor_json TEXT,
  input_json TEXT,                                   -- pointerType, pressure/tilt availability, device
  device_id TEXT,
  rev INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER
) STRICT;
CREATE INDEX idx_annotation_updated ON annotation(updated_at);

-- Which page/note-page/artifact an annotation lives on (denormalized for fast page loads)
CREATE TABLE annotation_target (
  annotation_id TEXT PRIMARY KEY REFERENCES annotation(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('source_page','note_page','artifact_block')),
  target_id TEXT NOT NULL
) STRICT;
CREATE INDEX idx_annotation_target ON annotation_target(target_type, target_id);

-- Text notes (My Notes). A low-assurance personal source: never auto-promoted to medical fact.
CREATE TABLE note (
  id TEXT PRIMARY KEY,                               -- client-generated
  node_id TEXT REFERENCES library_node(id),
  title TEXT,
  body_json TEXT NOT NULL,                           -- RichText
  anchor_json TEXT,                                  -- optional semantic/page anchor
  origin TEXT NOT NULL DEFAULT 'owner' CHECK (origin IN ('owner','ai_answer','handwriting_recognition')),
  ai_record_json TEXT,                               -- for saved AI answers: question, context, evidence ids, model, date, source versions
  rev INTEGER NOT NULL DEFAULT 1,
  base_rev INTEGER,
  conflict_of_id TEXT,                               -- set when this row preserves a conflicting copy
  device_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER
) STRICT;

-- Handwriting recognition: derived & correctable; never replaces ink.
CREATE TABLE ink_recognition (
  id TEXT PRIMARY KEY,
  annotation_ids_json TEXT NOT NULL,
  lang TEXT,
  text TEXT NOT NULL,
  confidence REAL,
  engine TEXT NOT NULL,
  corrected_text TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Media ─────────────────────────────
CREATE TABLE image_asset (
  id TEXT PRIMARY KEY,
  file_id TEXT REFERENCES stored_file(id),
  source_id TEXT REFERENCES source(id),
  version_id TEXT REFERENCES source_version(id),
  page_id TEXT REFERENCES source_page(id),
  region_id TEXT REFERENCES source_region(id),
  caption_region_id TEXT REFERENCES source_region(id),
  origin TEXT NOT NULL CHECK (origin IN ('source','external','generated','reorganized')),
  image_kind TEXT NOT NULL DEFAULT 'unknown' CHECK (image_kind IN (
    'clinical_photo','educational_drawing','diagram','radiology','histology','pathology','ecg','dermatology',
    'ophthalmology','table_image','generated_illustration','reorganized_diagram','unknown')),
  modality TEXT,
  anatomic_region TEXT,
  title TEXT,
  caption TEXT,
  original_url TEXT,
  fetched_at INTEGER,
  match_status TEXT NOT NULL DEFAULT 'unverified' CHECK (match_status IN ('unverified','matches','mismatch','owner_confirmed')),
  match_details_json TEXT,
  created_at INTEGER NOT NULL
) STRICT;

-- Non-destructive overlays on images: highlight, label masks (image occlusion), arrows.
CREATE TABLE media_overlay (
  id TEXT PRIMARY KEY,
  image_id TEXT NOT NULL REFERENCES image_asset(id),
  kind TEXT NOT NULL CHECK (kind IN ('highlight','occlusion_mask','arrow','label')),
  shape_json TEXT NOT NULL,                          -- normalized geometry on the original image
  label TEXT,
  certainty TEXT NOT NULL DEFAULT 'uncertain' CHECK (certainty IN ('from_caption','visually_confirmed','uncertain','owner')),
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE audio_asset (
  id TEXT PRIMARY KEY,
  source_id TEXT NOT NULL REFERENCES source(id),
  file_id TEXT NOT NULL REFERENCES stored_file(id),
  duration_ms INTEGER,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE transcript_segment (
  id TEXT PRIMARY KEY,
  audio_id TEXT NOT NULL REFERENCES audio_asset(id),
  start_ms INTEGER NOT NULL,
  end_ms INTEGER NOT NULL,
  text TEXT NOT NULL,
  corrected_text TEXT,
  confidence REAL,
  engine TEXT,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE media_region_link (
  id TEXT PRIMARY KEY,
  from_type TEXT NOT NULL,                           -- transcript_segment|annotation
  from_id TEXT NOT NULL,
  to_region_id TEXT,
  to_page_id TEXT,
  origin TEXT NOT NULL CHECK (origin IN ('manual','auto')),
  created_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Questions ─────────────────────────────
CREATE TABLE question (
  id TEXT PRIMARY KEY,
  origin_type TEXT NOT NULL CHECK (origin_type IN ('source','generated','owner')),
  current_version_id TEXT,
  status TEXT NOT NULL DEFAULT 'needs_review' CHECK (status IN ('draft','needs_review','ready','retired')),
  course_node_id TEXT REFERENCES library_node(id),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER
) STRICT;

-- Immutable once attempted. Corrections create a new version; attempts keep pointing at the old one.
CREATE TABLE question_version (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL REFERENCES question(id),
  version_no INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('raw_extraction','structured','owner_correction','translation','paraphrase','generated')),
  derived_from_version_id TEXT REFERENCES question_version(id),
  lang TEXT,
  qtype TEXT NOT NULL CHECK (qtype IN ('sba','multi_select','true_false','short_answer','essay','enumerate','compare','clinical_written')),
  item_type TEXT,                                    -- recall|vignette|diagnosis|investigation|next_step|management|mechanism|...
  stem_json TEXT NOT NULL,                           -- RichText
  stem_raw TEXT,                                     -- raw extracted text, unmodified
  has_negation INTEGER NOT NULL DEFAULT 0,
  negation_terms_json TEXT,
  shuffle_allowed INTEGER NOT NULL DEFAULT 1,
  extraction_status TEXT NOT NULL CHECK (extraction_status IN ('not_applicable','extracted','checks_passed','needs_review','owner_reviewed')),
  answer_status TEXT NOT NULL CHECK (answer_status IN ('source_key','missing_key','ai_derived','conflicting_key','unresolved','owner_key','not_applicable')),
  correct_option_ids_json TEXT,                      -- stable option ids (not labels, not display order)
  key_details_json TEXT,                             -- {key_entry_ids, conflicts, notes}
  explanation_json TEXT,                             -- RichText (+claims)
  distractor_explanations_json TEXT,                 -- {option_id: RichText}
  learning_objective TEXT,
  difficulty_est TEXT,                               -- estimated only
  rubric_json TEXT,                                  -- written questions
  owner_reviewed_fields_json TEXT,                   -- which fields the owner personally reviewed
  validation_json TEXT,                              -- check results summary
  created_by TEXT NOT NULL CHECK (created_by IN ('extraction','generation','owner','translation')),
  model TEXT,
  job_id TEXT,
  created_at INTEGER NOT NULL,
  UNIQUE (question_id, version_no)
) STRICT;

CREATE TABLE question_option (
  id TEXT PRIMARY KEY,                               -- stable id; keys reference this
  question_version_id TEXT NOT NULL REFERENCES question_version(id),
  option_key TEXT NOT NULL,                          -- stable internal key ('o1','o2',...) carried across versions
  source_label TEXT,                                 -- as printed: 'A', 'b', 'أ', 'ب', '1'
  ord INTEGER NOT NULL,                              -- source order
  text_json TEXT NOT NULL,
  raw_text TEXT,
  region_id TEXT REFERENCES source_region(id),
  pinned_position INTEGER NOT NULL DEFAULT 0,        -- e.g. "all of the above" must stay last
  UNIQUE (question_version_id, option_key)
) STRICT;

-- Where a question appears. A question can occur in several sources without losing any citation.
CREATE TABLE question_occurrence (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL REFERENCES question(id),
  question_version_id TEXT NOT NULL REFERENCES question_version(id),
  source_id TEXT NOT NULL REFERENCES source(id),
  source_version_id TEXT NOT NULL REFERENCES source_version(id),
  section_key TEXT NOT NULL DEFAULT '',              -- section identity for renumbered sections
  printed_number TEXT,
  page_ids_json TEXT NOT NULL,
  region_ids_json TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  UNIQUE (source_version_id, section_key, printed_number)
) STRICT;
CREATE INDEX idx_question_occurrence_q ON question_occurrence(question_id);

-- Answer key entries as found in sources. Bound by (version, section, number) — never number alone.
CREATE TABLE answer_key_entry (
  id TEXT PRIMARY KEY,
  source_version_id TEXT NOT NULL REFERENCES source_version(id),
  section_key TEXT NOT NULL DEFAULT '',
  printed_number TEXT NOT NULL,
  key_label TEXT NOT NULL,                           -- as printed
  mark_kind TEXT NOT NULL CHECK (mark_kind IN ('printed_key','key_table','circled_option','handwritten','highlight','unknown')),
  origin_known INTEGER NOT NULL DEFAULT 0,           -- 1 only when the mark is a declared official key
  page_id TEXT REFERENCES source_page(id),
  region_id TEXT REFERENCES source_region(id),
  matched_occurrence_id TEXT REFERENCES question_occurrence(id),
  created_at INTEGER NOT NULL,
  UNIQUE (source_version_id, section_key, printed_number, mark_kind)
) STRICT;

CREATE TABLE answer_evidence (
  id TEXT PRIMARY KEY,
  question_version_id TEXT NOT NULL REFERENCES question_version(id),
  option_id TEXT REFERENCES question_option(id),
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  role TEXT NOT NULL CHECK (role IN ('supports_answer','refutes_distractor','context','contradicts_key')),
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE question_lecture_link (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL REFERENCES question(id),
  lecture_source_id TEXT NOT NULL REFERENCES source(id),
  relation TEXT NOT NULL CHECK (relation IN ('directly_covered','strongly_related','partially_covered','course_related_only')),
  score REAL,
  reason TEXT NOT NULL,
  reason_json TEXT,                                  -- {concepts:[], matched_terms:[], lecture_page_ids:[], question_page_ids:[]}
  answerable_from_lecture INTEGER NOT NULL DEFAULT 0,
  origin TEXT NOT NULL CHECK (origin IN ('auto','owner')),
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','accepted','rejected')),
  decision_reason TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (question_id, lecture_source_id)
) STRICT;

CREATE TABLE question_duplicate (
  id TEXT PRIMARY KEY,
  question_a_id TEXT NOT NULL REFERENCES question(id),
  question_b_id TEXT NOT NULL REFERENCES question(id),
  kind TEXT NOT NULL CHECK (kind IN ('exact','near','paraphrase')),
  similarity REAL,
  blockers_json TEXT,                                -- e.g. negation differs, numbers differ, keys differ
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','confirmed','rejected')),
  created_at INTEGER NOT NULL,
  UNIQUE (question_a_id, question_b_id)
) STRICT;

CREATE VIRTUAL TABLE question_fts USING fts5(
  question_id UNINDEXED, version_id UNINDEXED, text,
  tokenize = 'unicode61 remove_diacritics 2'
);

-- ───────────────────────────── Practice & exams ─────────────────────────────
CREATE TABLE exam (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('practice','exam','time_pressure','simulation','revision')),
  config_json TEXT NOT NULL,                         -- scope, counts, ratios, difficulty, types
  policy_json TEXT NOT NULL,                         -- pause_allowed, hints, per_question_seconds... fixed at creation
  items_json TEXT NOT NULL,                          -- [{question_id, question_version_id, option_order:[option_id...]}]
  is_generated_simulation INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE exam_attempt (
  id TEXT PRIMARY KEY,
  exam_id TEXT NOT NULL REFERENCES exam(id),
  status TEXT NOT NULL CHECK (status IN ('in_progress','paused','completed','abandoned')),
  started_at INTEGER NOT NULL,
  finished_at INTEGER,
  elapsed_ms INTEGER NOT NULL DEFAULT 0,
  timer_json TEXT,
  current_index INTEGER NOT NULL DEFAULT 0,
  result_json TEXT,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE question_attempt (
  id TEXT PRIMARY KEY,                               -- client-generated; idempotent
  question_id TEXT NOT NULL REFERENCES question(id),
  question_version_id TEXT NOT NULL REFERENCES question_version(id),
  exam_attempt_id TEXT REFERENCES exam_attempt(id),
  selected_option_ids_json TEXT,
  is_correct INTEGER,                                -- NULL when the key is not resolved (not scored)
  scored INTEGER NOT NULL DEFAULT 0,
  confidence TEXT CHECK (confidence IN ('guess','unsure','confident')),
  hints_used INTEGER NOT NULL DEFAULT 0,
  solution_viewed_before_answer INTEGER NOT NULL DEFAULT 0,
  time_ms INTEGER,
  flagged INTEGER NOT NULL DEFAULT 0,
  mistake_type TEXT,
  mistake_origin TEXT CHECK (mistake_origin IN ('auto','owner')),
  device_id TEXT,
  answered_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_question_attempt_q ON question_attempt(question_id, answered_at);

CREATE TABLE written_attempt (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL REFERENCES question(id),
  question_version_id TEXT NOT NULL REFERENCES question_version(id),
  answer_text TEXT,
  answer_ink_ids_json TEXT,
  recognized_text TEXT,
  recognized_confirmed INTEGER NOT NULL DEFAULT 0,
  assessment_json TEXT,                              -- rubric points: correct/missing/wrong, est score, improved answer
  assessment_kind TEXT CHECK (assessment_kind IN ('rubric_score','qualitative_only')),
  answered_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE clinical_case (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('case','osce','viva')),
  scope_json TEXT NOT NULL,
  definition_json TEXT NOT NULL,                     -- stages, fixed patient facts, transitions, checklist/rubric
  is_generated INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL CHECK (status IN ('draft','needs_review','ready')),
  artifact_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE case_attempt (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL REFERENCES clinical_case(id),
  state_json TEXT NOT NULL,                          -- current stage + revealed facts (persisted, deterministic)
  events_json TEXT NOT NULL DEFAULT '[]',            -- append-only decision log
  assessment_json TEXT,
  status TEXT NOT NULL CHECK (status IN ('in_progress','completed','abandoned')),
  started_at INTEGER NOT NULL,
  finished_at INTEGER,
  updated_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Flashcards & spaced repetition ─────────────────────────────
CREATE TABLE flashcard (
  id TEXT PRIMARY KEY,                               -- client-generated allowed
  kind TEXT NOT NULL CHECK (kind IN ('basic','cloze','image_occlusion','mistake')),
  front_json TEXT NOT NULL,
  back_json TEXT NOT NULL,
  concept_id TEXT,
  topic_id TEXT,
  source_id TEXT,
  source_version_id TEXT,
  evidence_ids_json TEXT NOT NULL DEFAULT '[]',
  origin TEXT NOT NULL CHECK (origin IN ('owner','generated','from_mistake','from_selection')),
  origin_ref_json TEXT,                              -- e.g. {question_attempt_id}
  suspended INTEGER NOT NULL DEFAULT 0,
  buried_until INTEGER,
  rev INTEGER NOT NULL DEFAULT 1,
  device_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER
) STRICT;

-- Append-only, idempotent (id is client-generated). Schedules are DERIVED by replaying events.
CREATE TABLE review_event (
  id TEXT PRIMARY KEY,
  card_id TEXT NOT NULL REFERENCES flashcard(id),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 4),   -- 1 Again, 2 Hard, 3 Good, 4 Easy
  reviewed_at INTEGER NOT NULL,
  duration_ms INTEGER,
  device_id TEXT,
  context_json TEXT,
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_review_event_card ON review_event(card_id, reviewed_at);

-- Derived cache of the scheduler state (rebuildable from review_event + algorithm params).
CREATE TABLE review_state (
  card_id TEXT PRIMARY KEY REFERENCES flashcard(id),
  algorithm TEXT NOT NULL,                           -- e.g. 'fsrs-6 (ts-fsrs x.y.z)'
  state TEXT NOT NULL CHECK (state IN ('new','learning','review','relearning')),
  due_at INTEGER NOT NULL,
  stability REAL,
  difficulty REAL,
  reps INTEGER NOT NULL DEFAULT 0,
  lapses INTEGER NOT NULL DEFAULT 0,
  last_review_at INTEGER,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_review_state_due ON review_state(due_at);

-- ───────────────────────────── Personal learning ─────────────────────────────
CREATE TABLE weakness (
  id TEXT PRIMARY KEY,
  concept_id TEXT,
  topic_id TEXT,
  label TEXT NOT NULL,
  signals_json TEXT NOT NULL,                        -- [{type:'mcq'|'card'|'written'|'case'|'osce', ref_id, at, mistake_type}]
  score REAL NOT NULL DEFAULT 0,                     -- estimate, explained by reasons_json
  reasons_json TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','improving','resolved','dismissed')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE study_plan (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  exam_date TEXT,                                    -- YYYY-MM-DD in owner timezone
  config_json TEXT NOT NULL,                         -- subjects, available days, daily minutes, constraints
  status TEXT NOT NULL CHECK (status IN ('active','archived')),
  version INTEGER NOT NULL DEFAULT 1,
  last_rebalanced_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE plan_task (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES study_plan(id),
  day TEXT NOT NULL,                                 -- YYYY-MM-DD (owner timezone)
  kind TEXT NOT NULL CHECK (kind IN ('learn','review','mcq','flashcards','weakness','exam')),
  ref_json TEXT,
  minutes INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','done','skipped','moved')),
  moved_from_day TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_plan_task_day ON plan_task(plan_id, day);

-- Progress is separated: reading vs explanation coverage vs practice vs mastery estimate.
CREATE TABLE source_progress (
  source_id TEXT PRIMARY KEY REFERENCES source(id),
  pages_viewed_json TEXT NOT NULL DEFAULT '[]',
  reading_progress REAL NOT NULL DEFAULT 0,
  explanation_coverage REAL NOT NULL DEFAULT 0,
  practice_count INTEGER NOT NULL DEFAULT 0,
  mastery_estimate REAL,
  updated_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Sessions & contextual threads ─────────────────────────────
CREATE TABLE study_session (
  id TEXT PRIMARY KEY,
  source_id TEXT REFERENCES source(id),
  version_id TEXT REFERENCES source_version(id),
  mode TEXT NOT NULL DEFAULT 'learn' CHECK (mode IN ('learn','understand','practice','review','exam')),
  view TEXT NOT NULL DEFAULT 'original' CHECK (view IN ('original','study_book','split')),
  location_json TEXT NOT NULL,                       -- {page_index, block_key, zoom, scroll, rail:{open,width,tab}, split:{...}}
  scope_json TEXT,                                   -- current Source Lock
  device_id TEXT,
  rev INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_study_session_source ON study_session(source_id, updated_at);

CREATE TABLE contextual_thread (
  id TEXT PRIMARY KEY,
  source_id TEXT REFERENCES source(id),
  version_id TEXT REFERENCES source_version(id),
  anchor_json TEXT,                                  -- selection: page/region/block + quote
  scope_json TEXT NOT NULL,
  style TEXT NOT NULL DEFAULT 'detailed',
  title TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE message (
  id TEXT PRIMARY KEY,
  thread_id TEXT NOT NULL REFERENCES contextual_thread(id),
  role TEXT NOT NULL CHECK (role IN ('owner','assistant','system_notice')),
  content_json TEXT NOT NULL,                        -- RichText (assistant: blocks with claims)
  status TEXT NOT NULL DEFAULT 'final' CHECK (status IN ('draft','verifying','final','rejected','abstained')),
  abstain_reason TEXT,
  artifact_id TEXT,
  created_at INTEGER NOT NULL
) STRICT;

-- ───────────────────────────── Jobs, usage, sync, review queue ─────────────────────────────
CREATE TABLE processing_job (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,                                -- process_source|ocr_page|reindex|generate_study_book|extract_questions|match_questions|...
  status TEXT NOT NULL CHECK (status IN ('queued','running','waiting_for_input','partial','completed','failed','cancelled')),
  idempotency_key TEXT UNIQUE,
  input_json TEXT NOT NULL,
  output_json TEXT,
  progress_json TEXT,                                -- {stage, done, total, unit:'pages'|'items'|null}
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,
  error_code TEXT,
  error_detail TEXT,
  retryable INTEGER,
  run_after INTEGER NOT NULL DEFAULT 0,
  parent_job_id TEXT,
  version TEXT NOT NULL,                             -- job handler version
  created_at INTEGER NOT NULL,
  started_at INTEGER,
  heartbeat_at INTEGER,
  finished_at INTEGER,
  cancel_requested_at INTEGER
) STRICT;
CREATE INDEX idx_job_status ON processing_job(status, run_after);

CREATE TABLE job_checkpoint (
  job_id TEXT NOT NULL REFERENCES processing_job(id) ON DELETE CASCADE,
  step_key TEXT NOT NULL,                            -- e.g. 'extract:page:12'
  data_json TEXT,
  done_at INTEGER NOT NULL,
  PRIMARY KEY (job_id, step_key)
) STRICT;

CREATE TABLE usage_record (
  id TEXT PRIMARY KEY,
  job_id TEXT,
  task TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  input_tokens INTEGER,
  output_tokens INTEGER,
  estimated_cost_usd REAL,                           -- estimate, not an invoice
  latency_ms INTEGER,
  status TEXT NOT NULL,                              -- ok|error|schema_rejected|budget_blocked|fallback
  source_version_ids_json TEXT,
  rules_version TEXT,
  verification_status TEXT,
  request_ref TEXT,                                  -- provider request id (no content)
  created_at INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_usage_time ON usage_record(created_at);

-- Idempotent sync log: every client operation has a unique op_id and is applied at most once.
CREATE TABLE sync_operation (
  op_id TEXT PRIMARY KEY,
  device_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  op TEXT NOT NULL,                                  -- upsert|delete|append
  base_rev INTEGER,
  payload_json TEXT NOT NULL,
  result TEXT NOT NULL CHECK (result IN ('applied','merged','conflict_kept_both','duplicate','rejected')),
  result_detail TEXT,
  client_ts INTEGER,
  server_seq INTEGER NOT NULL,
  received_at INTEGER NOT NULL
) STRICT;

-- Monotonic change feed for pull-sync (server_seq per changed entity)
CREATE TABLE sync_change (
  seq INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  changed_at INTEGER NOT NULL
);
CREATE INDEX idx_sync_change_entity ON sync_change(entity_type, entity_id);

CREATE TABLE review_queue_item (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN (
    'ocr_error','unreadable_page','truncated_question','missing_option','conflicting_key','unofficial_mark',
    'ambiguous_figure','image_mismatch','uncertain_lecture_link','needs_reanchor','claim_unsupported',
    'question_validation_failed','metadata_suggestion','duplicate_suggestion','classification_suggestion')),
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  source_id TEXT,
  reason TEXT NOT NULL,                              -- specific, human-readable (Arabic)
  details_json TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','accepted','corrected','rejected','dismissed')),
  resolution_json TEXT,
  created_at INTEGER NOT NULL,
  resolved_at INTEGER
) STRICT;
CREATE INDEX idx_review_queue_status ON review_queue_item(status, kind);

-- Golden set / evaluation cases curated by the owner (repository fixtures live under fixtures/golden)
CREATE TABLE evaluation_case (
  id TEXT PRIMARY KEY,
  axis TEXT NOT NULL,                                -- text_accuracy|negation|options|key_binding|citation|support|...
  input_json TEXT NOT NULL,
  expected_json TEXT NOT NULL,
  reviewed_by TEXT,
  origin TEXT NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;

-- Universal search over owner content that is not a document chunk (notes, cards, messages, transcripts, recognized ink)
CREATE VIRTUAL TABLE owner_content_fts USING fts5(
  entity_type UNINDEXED, entity_id UNINDEXED, origin UNINDEXED, text,
  tokenize = 'unicode61 remove_diacritics 2'
);
