// Data track test helpers: a REAL library (Golden Set lecture + question source uploaded through the sources API
// into one course → processing → question extraction → lecture matching), owner writing pushed through the real
// sync handlers, a Study Book generated by the real job with the TEST-ONLY scripted provider (the generator copies
// evidence sentences verbatim and cites their aliases; the independent verifier is scripted "supported"), a
// practice attempt, and flashcards + review events.
import type { ExamCreateResponse, StudyBookView, SyncOpResult } from '@medlevo/shared';
import { newId } from '../../src/lib/ids';
import type { AuthHeaders, TestApp } from '../helpers/app';
import { createNode, uploadAndProcess, type QApp } from '../questions/helpers';
import { golden } from '../sources/helpers';
import { content, createStudyApp, regionsIn, S, ScriptedAi } from '../studybook/helpers';

export interface DataLib {
  t: TestApp;
  h: AuthHeaders;
  ai: ScriptedAi;
  courseId: string;
  lecture: { sourceId: string; versionId: string; pageIds: string[] };
  questions: { sourceId: string; versionId: string };
}

function bookGenerator(req: Parameters<Parameters<ScriptedAi['always']>[1]>[0]) {
  const regions = regionsIn(req.prompt);
  const blocks: unknown[] = [{ kind: 'heading', sentences: [S.n('قسم من كتاب الدراسة')] }];
  for (const r of regions) {
    if (!r.alias) continue;
    const quote = r.text.replace(/^\[E\d+\] \[R\d+\]\n/, '');
    const first = (quote.split(/(?<=[.!?؟])\s+/)[0] ?? '').trim().slice(0, 220);
    if (!first) continue;
    blocks.push({ kind: 'paragraph', sentences: [S.c(first, [r.alias], 'directly_stated')], explains_regions: [r.region] });
  }
  return content(blocks);
}

export async function dataLibrary(): Promise<DataLib> {
  const ai = new ScriptedAi();
  ai.always('study_book', bookGenerator);
  const t = await createStudyApp(ai);
  const h = await t.login();
  const q = Object.assign(t, { h }) as QApp;
  const course = await createNode(q, 'Surgery (TEST FIXTURE)', 'course');
  const lecture = await uploadAndProcess(q, course.id, 'lecture_appendicitis.pdf', golden('lecture_appendicitis.pdf'), 'lecture', 'Acute Appendicitis (TEST FIXTURE)');
  const questions = await uploadAndProcess(q, course.id, 'questions_surgery_course1.pdf', golden('questions_surgery_course1.pdf'), 'question_source', 'Surgery questions (TEST FIXTURE)');
  await t.ctx.jobs.drain();
  const pageIds = t.ctx.db.all<{ id: string }>('SELECT id FROM source_page WHERE version_id = ? ORDER BY page_index', [lecture.versionId]).map((r) => r.id);
  return { t, h, ai, courseId: course.id, lecture: { ...lecture, pageIds }, questions };
}

export async function push(lib: Pick<DataLib, 't' | 'h'>, ops: Array<{ entity_type: string; entity_id: string; op: 'upsert' | 'append' | 'delete'; payload: unknown; base_rev?: number | null }>): Promise<SyncOpResult[]> {
  const res = await lib.t.app.inject({
    method: 'POST',
    url: '/api/sync/push',
    headers: lib.h,
    payload: { ops: ops.map((o) => ({ op_id: newId(), device_id: 'DATA_TEST_DEVICE', client_ts: lib.t.ctx.clock.now(), base_rev: null, ...o })) },
  });
  if (res.statusCode !== 200) throw new Error(`push failed ${res.statusCode} ${res.body}`);
  return (res.json() as { results: SyncOpResult[] }).results;
}

export const rt = (text: string, dir: 'rtl' | 'ltr' = 'rtl') => ({ v: 1 as const, paragraphs: [{ dir, runs: [{ t: text }] }] });

export function pageAnchor(lib: DataLib, i: number) {
  return { type: 'page' as const, source_id: lib.lecture.sourceId, version_id: lib.lecture.versionId, page_id: lib.lecture.pageIds[i]!, page_index: i, space: 'page_norm' as const };
}

export interface OwnerData {
  inkId: string;
  highlightId: string;
  noteId: string;
  sessionId: string;
  cardIds: string[];
  eventIds: string[];
  attemptId: string | null;
  book: StudyBookView | null;
}

/** The owner's writing on the lecture, a study session, cards + reviews, a practice attempt and a Study Book. */
export async function writeOwnerData(lib: DataLib, opts: { book?: boolean; attempt?: boolean } = {}): Promise<OwnerData> {
  const inkId = newId();
  const highlightId = newId();
  const noteId = newId();
  const sessionId = newId();
  const results = await push(lib, [
    {
      entity_type: 'annotation',
      entity_id: inkId,
      op: 'append',
      payload: {
        kind: 'ink',
        tool: 'pen',
        anchor: pageAnchor(lib, 0),
        data: { v: 1, points: [[0.2, 0.3, 0, 0.5], [0.25, 0.31, 16, 0.6], [0.3, 0.32, 32, 0.55]], style: { tool: 'pen', color: 'ink-blue', width: 0.0025 }, bbox: { x: 0.2, y: 0.3, w: 0.1, h: 0.02 }, pressure_available: true, tilt_available: false },
        layer: 'ink',
        z: 0,
        locked: false,
      },
    },
    {
      entity_type: 'annotation',
      entity_id: highlightId,
      op: 'upsert',
      payload: { kind: 'text_highlight', anchor: pageAnchor(lib, 1), data: { v: 1, style: 'highlight', color: 'marker-yellow', rects: [{ x: 0.1, y: 0.2, w: 0.5, h: 0.02 }], quote: { exact: 'Murphy sign' } }, layer: 'highlight', z: 0, locked: false },
    },
    { entity_type: 'note', entity_id: noteId, op: 'upsert', payload: { title: 'ملاحظتي', body: rt('تذكّر علامة McBurney عند الفحص <b>مهم</b>'), anchor: pageAnchor(lib, 0), origin: 'owner' } },
    {
      entity_type: 'study_session',
      entity_id: sessionId,
      op: 'upsert',
      payload: { source_id: lib.lecture.sourceId, version_id: lib.lecture.versionId, mode: 'learn', view: 'original', location: { page_index: 1, page_id: lib.lecture.pageIds[1], zoom: 1.25, rotation: 0, layout: 'continuous' } },
    },
  ]);
  for (const r of results) if (r.result !== 'applied') throw new Error(`owner data not applied: ${JSON.stringify(r)}`);

  // flashcards + review events made from the lecture (learning track's tables; written directly here)
  const now = lib.t.ctx.clock.now();
  const cardIds = [newId(), newId()];
  const eventIds: string[] = [];
  for (const [i, id] of cardIds.entries()) {
    lib.t.ctx.db.run(
      `INSERT INTO flashcard (id, kind, front_json, back_json, source_id, source_version_id, evidence_ids_json, origin, rev, created_at, updated_at)
       VALUES (?, 'basic', ?, ?, ?, ?, '[]', 'owner', 1, ?, ?)`,
      [id, JSON.stringify(rt(`سؤال البطاقة ${i + 1}`)), JSON.stringify(rt(`جواب البطاقة ${i + 1}`)), lib.lecture.sourceId, lib.lecture.versionId, now, now],
    );
    for (const rating of i === 0 ? [3, 4] : [1]) {
      const eid = newId();
      eventIds.push(eid);
      lib.t.ctx.db.run('INSERT INTO review_event (id, card_id, rating, reviewed_at, duration_ms, device_id, created_at) VALUES (?, ?, ?, ?, 4000, ?, ?)', [eid, id, rating, now, 'DATA_TEST_DEVICE', now]);
    }
  }

  let attemptId: string | null = null;
  if (opts.attempt !== false) {
    const qid = lib.t.ctx.db.get<{ id: string }>(
      `SELECT q.id FROM question q JOIN question_version v ON v.id = q.current_version_id
        WHERE v.answer_status IN ('source_key','owner_key') AND q.status <> 'retired' ORDER BY q.created_at LIMIT 1`,
    )?.id;
    if (qid) {
      const ex = await lib.t.app.inject({ method: 'POST', url: '/api/exams', headers: lib.h, payload: { title: '', mode: 'practice', count: 1, question_ids: [qid] } });
      if (ex.statusCode === 200) {
        const session = (ex.json() as ExamCreateResponse).session;
        const item = session.items[0]!;
        attemptId = newId();
        const r = await push(lib, [
          {
            entity_type: 'question_attempt',
            entity_id: attemptId,
            op: 'append',
            payload: { question_id: item.question_id, question_version_id: item.question_version_id, exam_attempt_id: session.attempt.id, exam_item_index: 0, selected_option_ids: [item.options[0]!.id], confidence: 'unsure', answered_at: now },
          },
        ]);
        if (r[0]!.result !== 'applied') attemptId = null;
      }
    }
  }

  let book: StudyBookView | null = null;
  if (opts.book !== false) {
    const res = await lib.t.app.inject({
      method: 'POST',
      url: '/api/studybook/books',
      headers: lib.h,
      payload: { source_id: lib.lecture.sourceId, scope: { mode: 'lecture_only', lecture_source_id: lib.lecture.sourceId } },
    });
    if (res.statusCode !== 200) throw new Error(`study book failed ${res.statusCode} ${res.body}`);
    await lib.t.ctx.jobs.drain();
    const id = (res.json() as { book: StudyBookView }).book.artifact.id;
    book = (await lib.t.app.inject({ method: 'GET', url: `/api/studybook/books/${id}`, headers: lib.h })).json() as StudyBookView;
  }
  return { inkId, highlightId, noteId, sessionId, cardIds, eventIds, attemptId, book };
}

export async function getJson<T>(lib: Pick<DataLib, 't' | 'h'>, url: string): Promise<{ status: number; body: T; raw: string; headers: Record<string, unknown> }> {
  const res = await lib.t.app.inject({ method: 'GET', url, headers: lib.h });
  return { status: res.statusCode, body: (res.headers['content-type']?.toString().includes('json') ? res.json() : null) as T, raw: res.body, headers: res.headers };
}
