// MedLevo Study Book (§24) and summaries (§31): sectioned artifacts generated by a resumable job (§53, AC-25).
//
//  * sections come from the processed structure: heading regions start a section; no headings → one section per
//    page; very long sections are split at page boundaries. Each section keeps its source region ids.
//  * one job per artifact version; every section is generated, validated and written in ONE transaction together
//    with its 'complete' status, then checkpointed. An interrupted section is regenerated from scratch on retry —
//    never published half-finished — and finished sections are never generated twice.
//  * the artifact is 'generating' while sections run (finished sections can be read, clearly labelled as a
//    draft in progress with real section counts); 'published' when every section is done, 'partial' when some
//    failed (listed), 'failed' when none succeeded.
//  * regeneration creates a NEW version of the lineage; the previous published version stays until the new one
//    is published (then 'superseded', unless frozen). block_keys derive from section + region ids, so notes keep
//    their semantic anchors; anchors whose block disappeared are listed as needs_reanchor — never moved (AC-22).
//  * summaries use the same machinery with page batches and honest coverage (never «complete» when pages are
//    unprocessed / unreadable / excluded; last-minute & high-yield are labelled as selections).
import {
  JOB_STATUS_LABELS_AR,
  SELECTION_SUMMARY_TYPES,
  parseRichText,
  richTextToPlain,
  samePassage,
  SUMMARY_TYPE_LABELS_AR,
  pageDisplayLabel,
  type ExplanationRules,
  type JobView,
  type ReanchorItem,
  type SourceScope,
  type StudyBookSectionView,
  type StudyBookStatusResponse,
  type StudyBookView,
  type SummaryPreviewResponse,
  type SummaryType,
  type TwinEntry,
} from '@medlevo/shared';
import type { z } from 'zod';
import type { AppContext } from '../../context';
import { fromJson, toJson } from '../../db/db';
import { AppError, isAppError, JobError } from '../../lib/errors';
import { sha256 } from '../../lib/hash';
import { newId } from '../../lib/ids';
import type { JobRun } from '../jobs/queue';
import type { UntrustedBlock } from '../ai/types';
import {
  buildEvidencePack,
  cacheKey,
  fromRegion,
  resolveScope,
  retrieve,
  VERIFIER_VERSION,
  type ScopeReport,
} from '../evidence/services';
import { artifactView, findReusable, getArtifactRow, nextVersionNo, requireArtifact, type ArtifactRow } from './artifacts';
import { callModel, insertArtifact, keySettings, pinnedScope, requireAi, type ArtifactBase, type PackedEvidence } from './generate';
import { indexArtifact, processGenerated, recordBlockDependencies, stripPseudoCitations, writeBlocks, type PackContext } from './publish';
import { GENERATOR_VERSION, resolveRules } from './rules';
import type { studyBookBodySchema, summaryBodySchema } from './schema';
import { termsForTexts } from './terms';
import { shorten } from './text';

export const STUDY_BOOK_JOB = 'generate_study_book';
export const SUMMARY_JOB = 'generate_summary';
export const SECTION_JOB_VERSION = 'sections-1';

/** Test-only fault injection (never set in production). */
export interface StudybookHooks {
  /** called after a section was generated and validated, right before it is written */
  beforeSectionPublish?: (info: { artifactId: string; sectionKey: string; attempt: number }) => void | Promise<void>;
}

// ───────── planning ─────────
interface PlanRegion {
  id: string;
  kind: string;
  text: string | null;
  page_id: string;
  page_index: number;
  printed_label: string | null;
  page_kind: 'page' | 'slide' | 'image' | 'docx_section' | 'audio_segment';
  reading_order: number;
  status: string;
  text_origin: string | null;
}

export interface SectionPlan {
  section_key: string;
  ord: number;
  title: string | null;
  region_ids: string[];
  page_ids: string[];
}

const CONTENT_KINDS = new Set(['text_block', 'heading', 'paragraph', 'list_item', 'table', 'figure', 'caption', 'diagram', 'note', 'transcript']);
const MAX_SECTION_CHARS = 7000;

function versionRegions(ctx: AppContext, versionId: string, pageIndexes?: number[] | null): PlanRegion[] {
  const rows = ctx.db.all<PlanRegion>(
    `SELECT r.id, r.kind, r.text, r.page_id, p.page_index, p.printed_label, p.kind AS page_kind, r.reading_order, r.status, r.text_origin
       FROM source_region r JOIN source_page p ON p.id = r.page_id
      WHERE r.version_id = ? AND r.parent_region_id IS NULL AND r.status <> 'rejected' AND COALESCE(r.text_origin, '') <> 'vision'
        -- pages that are unreadable or not processed are never summarized / explained as if they were read
        AND p.processing_status IN ('ready','needs_review') AND p.text_status NOT IN ('no_text_found','needs_ocr','failed','pending')
      ORDER BY p.page_index, r.reading_order`,
    [versionId],
  );
  const wanted = pageIndexes?.length ? new Set(pageIndexes) : null;
  return rows.filter((r) => CONTENT_KINDS.has(r.kind) && (!wanted || wanted.has(r.page_index)) && (r.kind === 'figure' || (r.text ?? '').trim().length > 0));
}

function sectionKeyOf(versionId: string, firstRegionId: string): string {
  return `s${sha256(`${versionId}|${firstRegionId}`).slice(0, 14)}`;
}

/** Study Book sections from the processed structure (headings, else pages). Deterministic for a version. */
export function planStudyBookSections(ctx: AppContext, versionId: string): SectionPlan[] {
  const regions = versionRegions(ctx, versionId);
  const hasHeadings = regions.some((r) => r.kind === 'heading');
  type Draft = { title: string | null; regions: PlanRegion[] };
  const drafts: Draft[] = [];
  let cur: Draft | null = null;
  for (const r of regions) {
    const startNew = hasHeadings ? r.kind === 'heading' && (!cur || cur.regions.some((x) => x.kind !== 'heading')) : !cur || cur.regions[0]!.page_index !== r.page_index;
    if (startNew) {
      cur = { title: r.kind === 'heading' ? shorten(r.text ?? '', 160) : null, regions: [] };
      drafts.push(cur);
    } else if (!cur) {
      cur = { title: null, regions: [] };
      drafts.push(cur);
    }
    if (r.kind === 'heading' && cur.regions.every((x) => x.kind === 'heading') && cur.title && r.text && !cur.title.includes(r.text.trim())) {
      cur.title = shorten(`${cur.title} — ${r.text}`, 160);
    }
    cur.regions.push(r);
  }
  // split very long sections at page boundaries
  const split: Draft[] = [];
  for (const d of drafts) {
    let part: Draft = { title: d.title, regions: [] };
    let chars = 0;
    for (const r of d.regions) {
      const len = (r.text ?? '').length;
      if (part.regions.length && chars + len > MAX_SECTION_CHARS && part.regions[part.regions.length - 1]!.page_index !== r.page_index) {
        split.push(part);
        part = { title: d.title ? `${d.title} (تابع)` : null, regions: [] };
        chars = 0;
      }
      part.regions.push(r);
      chars += len;
    }
    if (part.regions.length) split.push(part);
  }
  return split
    .filter((d) => d.regions.some((r) => r.kind !== 'heading'))
    .map((d, ord) => ({
      section_key: sectionKeyOf(versionId, d.regions[0]!.id),
      ord,
      title: d.title ?? `${pageDisplayLabel({ page_index: d.regions[0]!.page_index, printed_label: d.regions[0]!.printed_label, kind: d.regions[0]!.page_kind })}`,
      region_ids: d.regions.map((r) => r.id),
      page_ids: [...new Set(d.regions.map((r) => r.page_id))],
    }));
}

interface PageStat {
  id: string;
  page_index: number;
  printed_label: string | null;
  kind: PlanRegion['page_kind'];
  processing_status: string;
  text_status: string;
}

function versionPages(ctx: AppContext, versionId: string): PageStat[] {
  return ctx.db.all<PageStat>('SELECT id, page_index, printed_label, kind, processing_status, text_status FROM source_page WHERE version_id = ? ORDER BY page_index', [versionId]);
}

function pageLabel(p: Pick<PageStat, 'page_index' | 'printed_label' | 'kind'>): string {
  return pageDisplayLabel({ page_index: p.page_index, printed_label: p.printed_label, kind: p.kind });
}

function unreadable(p: PageStat): boolean {
  return p.processing_status === 'failed' || ['no_text_found', 'needs_ocr', 'failed'].includes(p.text_status);
}
function unprocessed(p: PageStat): boolean {
  return !unreadable(p) && ['pending', 'processing', 'skipped'].includes(p.processing_status);
}

// ───────── views ─────────
const SECTION_STATUS_AR: Record<StudyBookSectionView['status'], string> = {
  pending: 'في الانتظار',
  generating: 'قيد التوليد',
  complete: 'مكتمل',
  abstained: 'لا أدلة كافية',
  failed: 'فشل',
};

interface SectionRow {
  artifact_id: string;
  section_key: string;
  ord: number;
  title: string | null;
  region_ids_json: string;
  page_ids_json: string;
  status: StudyBookSectionView['status'];
  block_count: number;
  attempts: number;
  detail_json: string | null;
  updated_at: number;
}

function sectionRows(ctx: AppContext, artifactId: string): SectionRow[] {
  return ctx.db.all<SectionRow>('SELECT * FROM artifact_section WHERE artifact_id = ? ORDER BY ord', [artifactId]);
}

function sectionView(ctx: AppContext, s: SectionRow): StudyBookSectionView {
  const pageIds = fromJson<string[]>(s.page_ids_json, []) ?? [];
  const pages = pageIds.length
    ? ctx.db.all<PageStat>(`SELECT id, page_index, printed_label, kind, processing_status, text_status FROM source_page WHERE id IN (${pageIds.map(() => '?').join(',')}) ORDER BY page_index`, pageIds)
    : [];
  const detail = fromJson<{ reason_ar?: string }>(s.detail_json);
  return {
    section_key: s.section_key,
    ord: s.ord,
    title: s.title,
    status: s.status,
    status_label_ar: SECTION_STATUS_AR[s.status],
    block_count: s.block_count,
    page_indexes: pages.map((p) => p.page_index),
    page_labels_ar: pages.map((p) => pageLabel(p)),
    detail_ar: detail?.reason_ar ?? null,
  };
}

function reanchorItems(ctx: AppContext, artifactId: string): ReanchorItem[] {
  const rows = ctx.db.all<{ target_kind: 'annotation' | 'note'; target_id: string; block_key: string; previous_version_no: number | null; status: 'matched' | 'needs_reanchor' }>(
    'SELECT target_kind, target_id, block_key, previous_version_no, status FROM artifact_reanchor WHERE artifact_id = ? ORDER BY status DESC, target_kind, target_id',
    [artifactId],
  );
  const keys = new Set(ctx.db.all<{ block_key: string }>('SELECT block_key FROM content_block WHERE artifact_id = ?', [artifactId]).map((r) => r.block_key));
  return rows.map((r) => ({
    ...r,
    reason_ar:
      r.status === 'matched'
        ? 'ما زالت الفقرة نفسها موجودة في هذه النسخة؛ بقيت الملاحظة مرتبطة بها.'
        : keys.has(r.block_key)
          ? `${r.target_kind === 'note' ? 'ملاحظة' : 'كتابة'} على فقرة${r.previous_version_no ? ` من النسخة ${r.previous_version_no}` : ''} تغيّر نصها في هذه النسخة (فقرة أخرى في مكانها)؛ لم تُنقل إليها، وحُفظت كما هي وتحتاج إعادة ربط.`
          : `${r.target_kind === 'note' ? 'ملاحظة' : 'كتابة'} على فقرة${r.previous_version_no ? ` من النسخة ${r.previous_version_no}` : ''} لم تعد موجودة في هذه النسخة؛ حُفظت كما هي وتحتاج إعادة ربط.`,
  }));
}

/** Lazy reconcile: a 'generating' artifact whose job ended (failed / cancelled) is finalized honestly. */
function reconcileWithJob(ctx: AppContext, a: ArtifactRow): ArtifactRow {
  if (a.status !== 'generating' || !a.job_id) return a;
  const job = ctx.jobs.get(a.job_id);
  if (!job || job.status === 'failed' || job.status === 'cancelled') {
    finalizeSectioned(ctx, a.id, { jobStatus: job?.status ?? 'failed', jobError: job?.error?.message ?? null });
    return getArtifactRow(ctx, a.id)!;
  }
  return a;
}

export function bookView(ctx: AppContext, artifactId: string): StudyBookView {
  const row = reconcileWithJob(ctx, requireArtifact(ctx, artifactId));
  const artifact = artifactView(ctx, row);
  const sections = sectionRows(ctx, row.id).map((s) => sectionView(ctx, s));
  const job: JobView | null = row.job_id ? ctx.jobs.get(row.job_id) : null;
  const twin: TwinEntry[] = artifact.blocks.map((b) => ({ block_key: b.block_key, section_key: b.section_key, page_indexes: b.meta?.page_indexes ?? [] }));
  const newer = ctx.db.get<{ id: string }>(
    `SELECT id FROM artifact WHERE lineage_id = ? AND version_no > ? AND status IN ('published','partial') ORDER BY version_no DESC LIMIT 1`,
    [row.lineage_id, row.version_no],
  );
  return {
    artifact,
    sections,
    job: job ? { ...job, input: undefined, output: undefined } : null,
    progress: {
      sections_total: sections.length,
      sections_complete: sections.filter((s) => s.status === 'complete').length,
      sections_abstained: sections.filter((s) => s.status === 'abstained').length,
      sections_failed: sections.filter((s) => s.status === 'failed').length,
    },
    twin,
    reanchor: reanchorItems(ctx, row.id),
    newer_version_id: newer?.id ?? null,
  };
}

/** The Study Book shown for a source by default: frozen > latest published/partial > latest in progress. */
export function bookForSource(ctx: AppContext, sourceId: string): StudyBookStatusResponse {
  const pick = ctx.db.get<{ id: string }>(
    `SELECT id FROM artifact WHERE primary_source_id = ? AND kind = 'study_book'
      ORDER BY CASE WHEN is_frozen = 1 AND status IN ('published','partial','stale') THEN 0
                    WHEN status IN ('published','partial','stale') THEN 1
                    WHEN status = 'generating' THEN 2 ELSE 3 END, version_no DESC, created_at DESC LIMIT 1`,
    [sourceId],
  );
  const can = canGenerateBook(ctx, sourceId);
  return { book: pick ? bookView(ctx, pick.id) : null, can_generate: can };
}

export function canGenerateBook(ctx: AppContext, sourceId: string): { available: boolean; reason_ar: string | null } {
  const cap = ctx.capabilities.get('ai.study_book');
  if (cap.state !== 'available') return { available: false, reason_ar: cap.reason_ar ?? 'ميزة كتاب الدراسة غير متاحة.' };
  if (!ctx.ai.isAvailable('study_book')) return { available: false, reason_ar: ctx.ai.status().tasks.study_book.reason_ar ?? 'خدمة الذكاء الاصطناعي غير متاحة.' };
  const s = ctx.db.get<{ deleted_at: number | null; current_version_id: string | null; frozen_version_id: string | null }>('SELECT deleted_at, current_version_id, frozen_version_id FROM source WHERE id = ?', [sourceId]);
  if (!s || s.deleted_at !== null) return { available: false, reason_ar: 'المصدر غير موجود أو في سلة المحذوفات.' };
  const v = s.frozen_version_id ?? s.current_version_id;
  const st = v ? ctx.db.get<{ processing_status: string }>('SELECT processing_status FROM source_version WHERE id = ?', [v]) : undefined;
  if (!st || ['pending', 'processing'].includes(st.processing_status)) return { available: false, reason_ar: 'لم تكتمل معالجة المصدر بعد؛ يُولَّد كتاب الدراسة من البنية المعالجة.' };
  return { available: true, reason_ar: null };
}

// ───────── create ─────────
interface SectionedParams {
  mode: 'study_book' | 'summary';
  source_id: string;
  version_id: string;
  /** the owner's scope request pinned to the versions it resolved to (re-resolved by the job; must match) */
  scope_request: SourceScope;
  /** effective rules snapshot (the job never re-reads settings that changed meanwhile) */
  rules: ExplanationRules;
  style: 'detailed';
  summary_type?: SummaryType;
  instruction?: string | null;
  page_indexes?: number[] | null;
  language: 'ar';
  /** progressive generation: the sections this run generates (the others stay pending until «resume») */
  only_sections?: string[];
}

function assertSourceVersionInScope(scope: ScopeReport, sourceId: string, versionId: string): void {
  if (scope.versionBySource[sourceId] !== versionId) {
    throw new AppError('OUT_OF_SCOPE', 'نسخة المصدر المطلوبة ليست النسخة المقفلة في النطاق (Source Lock). اختر نطاقًا يشمل هذه النسخة صراحةً.', 409);
  }
}

function sourceVersionFor(ctx: AppContext, sourceId: string, versionId: string | undefined, scope: ScopeReport): { title: string; versionId: string; status: string } {
  const s = ctx.db.get<{ title: string; deleted_at: number | null }>('SELECT title, deleted_at FROM source WHERE id = ?', [sourceId]);
  if (!s || s.deleted_at !== null) throw new AppError('NOT_FOUND', 'المصدر غير موجود أو في سلة المحذوفات.', 404);
  const vid = versionId ?? scope.versionBySource[sourceId];
  if (!vid) throw new AppError('OUT_OF_SCOPE', 'المصدر ليس ضمن النطاق المقفل.', 409);
  assertSourceVersionInScope(scope, sourceId, vid);
  const v = ctx.db.get<{ processing_status: string; source_id: string }>('SELECT processing_status, source_id FROM source_version WHERE id = ?', [vid]);
  if (!v || v.source_id !== sourceId) throw new AppError('VALIDATION_FAILED', 'النسخة لا تخص هذا المصدر.', 400);
  return { title: s.title.replace(/[\r\n\t]+/g, ' ').trim(), versionId: vid, status: v.processing_status };
}

function insertSections(ctx: AppContext, artifactId: string, plans: SectionPlan[]): void {
  const now = ctx.clock.now();
  for (const p of plans) {
    ctx.db.run(
      `INSERT INTO artifact_section (artifact_id, section_key, ord, title, region_ids_json, page_ids_json, status, block_count, attempts, detail_json, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, 'pending', 0, 0, NULL, ?)`,
      [artifactId, p.section_key, p.ord, p.title, toJson(p.region_ids), toJson(p.page_ids), now],
    );
  }
}

export function createStudyBook(ctx: AppContext, body: z.infer<typeof studyBookBodySchema>): { book: StudyBookView; cached: boolean } {
  const scope = resolveScope(ctx, body.scope);
  const src = sourceVersionFor(ctx, body.source_id, body.version_id, scope);
  if (['pending', 'processing'].includes(src.status)) throw new AppError('CONFLICT', 'لم تكتمل معالجة المصدر بعد؛ يُولَّد كتاب الدراسة من البنية المعالجة.', 409);
  requireAi(ctx, 'study_book');
  const rules = resolveRules(ctx, { sourceId: body.source_id, overrides: body.rules ?? null });
  const plans = planStudyBookSections(ctx, src.versionId);
  if (plans.length === 0) throw new AppError('INSUFFICIENT_EVIDENCE', 'لا توجد في هذه النسخة مقاطع نصية معالجة يمكن بناء كتاب الدراسة منها (قد تكون الصفحات غير مقروءة).', 422);
  // progressive generation: only these sections now. The version still holds EVERY section (the others stay
  // «pending», the version is «partial» and never supersedes a complete one); «resume» generates the rest.
  let only: string[] | null = null;
  if (body.section_keys?.length) {
    const wanted = new Set(body.section_keys);
    only = plans.filter((p) => wanted.has(p.section_key)).map((p) => p.section_key);
    if (only.length === 0) throw new AppError('VALIDATION_FAILED', 'الأقسام المطلوبة غير موجودة في هذه النسخة من المصدر.', 400, { section_keys: body.section_keys });
    if (only.length === plans.length) only = null;
  }
  const key = cacheKey(ctx, {
    kind: 'study_book',
    scope,
    rulesVersion: rules.rules_version,
    generatorVersion: GENERATOR_VERSION,
    verifierVersion: VERIFIER_VERSION,
    level: rules.level,
    language: 'ar',
    dialect: rules.dialect,
    settings: keySettings(ctx, 'study_book', { style: 'detailed' }),
    params: { source_id: body.source_id, version_id: src.versionId, sections: plans.map((p) => p.section_key), only },
  });
  if (!body.regenerate) {
    const cached = findReusable(ctx, key, 'study_book');
    if (cached) return { book: bookView(ctx, cached.id), cached: true };
  }
  // the same request already running → that one (idempotent)
  const running = ctx.db.get<{ id: string }>(`SELECT id FROM artifact WHERE cache_key = ? AND kind = 'study_book' AND status = 'generating' ORDER BY created_at DESC LIMIT 1`, [key]);
  if (running) return { book: bookView(ctx, running.id), cached: false };

  const prev = ctx.db.get<{ lineage_id: string }>(`SELECT lineage_id FROM artifact WHERE primary_source_id = ? AND kind = 'study_book' ORDER BY created_at DESC LIMIT 1`, [body.source_id]);
  const lineage = prev ? { lineageId: prev.lineage_id, versionNo: nextVersionNo(ctx, prev.lineage_id), parentArtifactId: null } : null;
  const params: SectionedParams = {
    mode: 'study_book',
    source_id: body.source_id,
    version_id: src.versionId,
    scope_request: pinnedScope(body.scope as SourceScope, scope),
    rules,
    style: 'detailed',
    language: 'ar',
    ...(only ? { only_sections: only } : {}),
  };
  const id = startSectioned(ctx, {
    base: { kind: 'study_book', title: `كتاب الدراسة — ${src.title}`, primarySourceId: body.source_id, scope, rules, cacheKey: key, params: params as unknown as Record<string, unknown>, anchor: null, lineage },
    plans,
    jobKind: STUDY_BOOK_JOB,
    coverage: { sections_total: plans.length, sections_covered: 0, pages_total: versionPages(ctx, src.versionId).length, pages_covered: 0 },
  });
  return { book: bookView(ctx, id), cached: false };
}

function startSectioned(ctx: AppContext, o: { base: ArtifactBase; plans: SectionPlan[]; jobKind: string; coverage: Record<string, unknown> }): string {
  const id = ctx.db.tx(() => {
    const aid = insertArtifact(ctx, o.base, 'generating');
    ctx.db.run('UPDATE artifact SET coverage_json = ? WHERE id = ?', [toJson(o.coverage), aid]);
    insertSections(ctx, aid, o.plans);
    return aid;
  });
  const job = ctx.jobs.enqueue(o.jobKind, { artifact_id: id }, { idempotencyKey: `${o.jobKind}:${id}:1` });
  ctx.db.run('UPDATE artifact SET job_id = ?, updated_at = ? WHERE id = ?', [job.id, ctx.clock.now(), id]);
  return id;
}

/** Resume a partial / failed / cancelled sectioned artifact: failed & pending sections run again (new job). */
export function resumeSectioned(ctx: AppContext, artifactId: string): StudyBookView {
  const a = reconcileWithJob(ctx, requireArtifact(ctx, artifactId));
  if (!['study_book', 'summary'].includes(a.kind)) throw new AppError('BAD_REQUEST', 'هذا المحتوى ليس كتاب دراسة أو ملخصًا.', 400);
  if (a.status === 'generating') return bookView(ctx, a.id);
  if (!['partial', 'failed'].includes(a.status)) throw new AppError('CONFLICT', 'لا يوجد ما يُستأنف: كل الأقسام مكتملة.', 409);
  requireAi(ctx, a.kind === 'summary' ? 'summarize' : 'study_book');
  const n = (ctx.db.get<{ n: number }>(`SELECT COUNT(*) AS n FROM processing_job WHERE idempotency_key LIKE ?`, [`%:${a.id}:%`])?.n ?? 0) + 1;
  const params = fromJson<SectionedParams>(a.params_json);
  ctx.db.tx(() => {
    ctx.db.run(`UPDATE artifact_section SET status = 'pending', updated_at = ? WHERE artifact_id = ? AND status IN ('failed','generating')`, [ctx.clock.now(), a.id]);
    ctx.db.run(`UPDATE artifact SET status = 'generating', updated_at = ? WHERE id = ?`, [ctx.clock.now(), a.id]);
    // resuming a progressive generation generates every remaining section
    if (params?.only_sections) {
      const { only_sections: _o, ...rest } = params;
      ctx.db.run('UPDATE artifact SET params_json = ? WHERE id = ?', [toJson(rest), a.id]);
    }
  });
  const job = ctx.jobs.enqueue(a.kind === 'summary' ? SUMMARY_JOB : STUDY_BOOK_JOB, { artifact_id: a.id }, { idempotencyKey: `${a.kind === 'summary' ? SUMMARY_JOB : STUDY_BOOK_JOB}:${a.id}:${n}` });
  ctx.db.run('UPDATE artifact SET job_id = ? WHERE id = ?', [job.id, a.id]);
  return bookView(ctx, a.id);
}

export function cancelSectioned(ctx: AppContext, artifactId: string): StudyBookView {
  const a = requireArtifact(ctx, artifactId);
  if (a.status !== 'generating' || !a.job_id) throw new AppError('CONFLICT', 'لا توجد عملية توليد جارية لهذا المحتوى.', 409);
  const job = ctx.jobs.get(a.job_id);
  if (job && !['completed', 'partial', 'failed', 'cancelled'].includes(job.status)) ctx.jobs.cancel(a.job_id);
  const after = ctx.jobs.get(a.job_id);
  if (after?.status === 'cancelled') finalizeSectioned(ctx, a.id, { jobStatus: 'cancelled', jobError: null });
  return bookView(ctx, a.id);
}

// ───────── summaries (§31) ─────────
function summaryPlans(ctx: AppContext, versionId: string, pageIndexes: number[] | null): SectionPlan[] {
  const regions = versionRegions(ctx, versionId, pageIndexes);
  const plans: SectionPlan[] = [];
  let cur: PlanRegion[] = [];
  let chars = 0;
  const flush = () => {
    if (!cur.length) return;
    const first = cur[0]!;
    const last = cur[cur.length - 1]!;
    const label = first.page_index === last.page_index ? pageLabel({ page_index: first.page_index, printed_label: first.printed_label, kind: first.page_kind }) : `${pageLabel({ page_index: first.page_index, printed_label: first.printed_label, kind: first.page_kind })} – ${pageLabel({ page_index: last.page_index, printed_label: last.printed_label, kind: last.page_kind })}`;
    plans.push({ section_key: sectionKeyOf(versionId, `sum|${first.id}`), ord: plans.length, title: label, region_ids: cur.map((r) => r.id), page_ids: [...new Set(cur.map((r) => r.page_id))] });
    cur = [];
    chars = 0;
  };
  let lastPage = -1;
  for (const r of regions) {
    const len = (r.text ?? '').length;
    if (cur.length && r.page_index !== lastPage && chars + len > 6000) flush();
    cur.push(r);
    chars += len;
    lastPage = r.page_index;
  }
  flush();
  return plans;
}

export function summaryPreview(ctx: AppContext, body: z.infer<typeof summaryBodySchema>): SummaryPreviewResponse {
  const scope = resolveScope(ctx, body.scope);
  const src = sourceVersionFor(ctx, body.source_id, body.version_id, scope);
  const pages = versionPages(ctx, src.versionId);
  const wanted = body.page_indexes?.length ? new Set(body.page_indexes) : null;
  const selected = wanted ? pages.filter((p) => wanted.has(p.page_index)) : pages;
  const missingIndexes = wanted ? [...wanted].filter((i) => !pages.some((p) => p.page_index === i)) : [];
  const unread = selected.filter(unreadable);
  const unproc = selected.filter(unprocessed);
  const withText = new Set(versionRegions(ctx, src.versionId, wanted ? [...wanted] : null).map((r) => r.page_index));
  const ready = selected.filter((p) => !unreadable(p) && !unprocessed(p) && withText.has(p.page_index));
  const empty = selected.filter((p) => !unreadable(p) && !unprocessed(p) && !withText.has(p.page_index));
  const notes: string[] = [];
  if (unread.length) notes.push(`صفحات غير مقروءة لن يغطيها الملخص: ${unread.map(pageLabel).join('، ')}.`);
  if (unproc.length) notes.push(`صفحات لم تكتمل معالجتها بعد: ${unproc.map(pageLabel).join('، ')}.`);
  if (empty.length) notes.push(`صفحات بلا نص قابل للتلخيص: ${empty.map(pageLabel).join('، ')}.`);
  if (missingIndexes.length) notes.push(`صفحات مطلوبة غير موجودة في هذه النسخة: ${missingIndexes.map((i) => i + 1).join('، ')}.`);
  const isSelection = SELECTION_SUMMARY_TYPES.includes(body.type);
  if (isSelection) notes.push('هذا النوع انتقاء للموضوعات الأهم وليس بديلًا يغطي كل التفاصيل.');
  if (body.topic_ids?.length) notes.push('اختيار الموضوعات غير مدعوم بعد في الملخص؛ سيُلخَّص ما حددته من صفحات فقط.');
  return {
    type: body.type,
    type_label_ar: SUMMARY_TYPE_LABELS_AR[body.type],
    source_id: body.source_id,
    version_id: src.versionId,
    scope_describe_ar: scope.describeAr,
    pages_selected: selected.length + missingIndexes.length,
    pages_ready: ready.length,
    pages_unreadable: unread.map((p) => p.page_index),
    pages_unprocessed: unproc.map((p) => p.page_index),
    will_be_complete: !isSelection && unread.length === 0 && unproc.length === 0 && empty.length === 0 && missingIndexes.length === 0 && ready.length > 0,
    is_selection: isSelection,
    notes_ar: notes,
  };
}

export function createSummary(ctx: AppContext, body: z.infer<typeof summaryBodySchema>): { book: StudyBookView; cached: boolean } {
  const scope = resolveScope(ctx, body.scope);
  const src = sourceVersionFor(ctx, body.source_id, body.version_id, scope);
  requireAi(ctx, 'summarize');
  const preview = summaryPreview(ctx, body);
  const rules = resolveRules(ctx, { sourceId: body.source_id });
  const pageIndexes = body.page_indexes?.length ? [...new Set(body.page_indexes)].sort((a, b) => a - b) : null;
  const plans = summaryPlans(ctx, src.versionId, pageIndexes);
  if (plans.length === 0) throw new AppError('INSUFFICIENT_EVIDENCE', 'لا يوجد في الصفحات المحددة نص معالَج يمكن تلخيصه.', 422, { notes: preview.notes_ar });
  const key = cacheKey(ctx, {
    kind: `summary:${body.type}`,
    scope,
    rulesVersion: rules.rules_version,
    generatorVersion: GENERATOR_VERSION,
    verifierVersion: VERIFIER_VERSION,
    level: rules.level,
    language: 'ar',
    dialect: rules.dialect,
    settings: keySettings(ctx, 'summarize'),
    params: { source_id: body.source_id, version_id: src.versionId, pages: pageIndexes, instruction: body.instruction?.trim() || null },
  });
  const cached = findReusable(ctx, key, 'summary');
  if (cached) return { book: bookView(ctx, cached.id), cached: true };
  const running = ctx.db.get<{ id: string }>(`SELECT id FROM artifact WHERE cache_key = ? AND kind = 'summary' AND status = 'generating' ORDER BY created_at DESC LIMIT 1`, [key]);
  if (running) return { book: bookView(ctx, running.id), cached: false };

  const pages = versionPages(ctx, src.versionId);
  const selected = pageIndexes ? pages.filter((p) => pageIndexes.includes(p.page_index)) : pages;
  const range = selected.length ? (selected.length === 1 ? pageLabel(selected[0]!) : `${pageLabel(selected[0]!)} – ${pageLabel(selected[selected.length - 1]!)}`) : '';
  const params: SectionedParams = {
    mode: 'summary',
    source_id: body.source_id,
    version_id: src.versionId,
    scope_request: pinnedScope(body.scope as SourceScope, scope),
    rules,
    style: 'detailed',
    summary_type: body.type,
    instruction: body.instruction?.trim() || null,
    page_indexes: pageIndexes,
    language: 'ar',
  };
  const missing = preview.notes_ar.filter((n) => !n.startsWith('هذا النوع'));
  const id = startSectioned(ctx, {
    base: {
      kind: 'summary',
      title: `ملخص ${SUMMARY_TYPE_LABELS_AR[body.type]} — ${src.title}${range ? ` (${range})` : ''}`,
      primarySourceId: body.source_id,
      scope,
      rules,
      cacheKey: key,
      params: { ...(params as unknown as Record<string, unknown>), is_selection: preview.is_selection, preview_notes: preview.notes_ar },
      anchor: null,
    },
    plans,
    jobKind: SUMMARY_JOB,
    coverage: { pages_total: preview.pages_selected, pages_covered: 0, sections_total: plans.length, sections_covered: 0, ...(missing.length ? { missing_ar: missing } : {}) },
  });
  return { book: bookView(ctx, id), cached: false };
}

const SUMMARY_INSTRUCTIONS: Record<SummaryType, string> = {
  quick: 'QUICK summary: a few "list" blocks with only the key points of these pages.',
  detailed: 'DETAILED summary: "heading" blocks per topic and "paragraph"/"list" blocks, keeping every condition and exception.',
  exam: 'EXAM summary: definitions, discriminating features, values and classic pitfalls ("exam_pearl" and "list" blocks).',
  clinical: 'CLINICAL summary: presentation, examination, investigations, management and complications as stated ("clinical_note" / "list" blocks).',
  last_minute: 'LAST-MINUTE review: a short SELECTION of the most testable points ("list" blocks). It is a selection, not full coverage.',
  high_yield: 'HIGH-YIELD: a SELECTION of the highest-yield points ("list" / "exam_pearl" blocks). It is a selection, not full coverage.',
  tables_only: 'TABLES ONLY: only "comparison_table" blocks (header = aspects / items present in the evidence; cells with claims).',
  flowcharts: 'FLOWCHARTS: only "flowchart" blocks (ordered steps, one sentence per step, arrows implied by order) where the evidence describes a sequence or algorithm.',
  mind_map: 'MIND MAP: a hierarchical outline — a "heading" block per main concept followed by "list" blocks of its sub-points.',
  custom: 'CUSTOM summary following the owner instruction (structure only; it never overrides the evidence contract).',
};

// ───────── the job ─────────
export interface SectionJobInput {
  artifact_id: string;
}

/** Provider failures that concern this section's content only (the next section may well succeed). */
const SECTION_LEVEL_PROVIDER_ERRORS = new Set(['refusal', 'truncated', 'too_large']);

/** A classified provider failure surfaced by the orchestrator (AI_PROVIDER_ERROR with details.provider_error). */
function providerFailure(e: unknown): { kind: string; retryable: boolean } | null {
  if (!isAppError(e) || e.code !== 'AI_PROVIDER_ERROR') return null;
  const d = e.details as { provider_error?: unknown; retryable?: unknown } | undefined;
  if (!d || typeof d.provider_error !== 'string') return null;
  return { kind: d.provider_error, retryable: d.retryable === true };
}

function toJobError(e: unknown): JobError | null {
  if (!isAppError(e)) return null;
  if (['AI_NOT_CONFIGURED', 'AI_BUDGET_EXCEEDED', 'OUT_OF_SCOPE', 'FEATURE_DISABLED'].includes(e.code)) return new JobError(e.code, e.messageAr, { retryable: false });
  return null;
}

export function sectionJobHandler(ctx: AppContext, hooks: StudybookHooks = {}) {
  return async (run: JobRun<SectionJobInput>): Promise<{ artifact_id: string; status: string }> => {
    const a = requireArtifact(ctx, run.input.artifact_id);
    if (a.status !== 'generating') return { artifact_id: a.id, status: a.status };
    const params = fromJson<SectionedParams>(a.params_json)!;
    let scope: ScopeReport;
    try {
      scope = resolveScope(ctx, params.scope_request);
    } catch (e) {
      finalizeSectioned(ctx, a.id, { jobStatus: 'failed', jobError: isAppError(e) ? e.messageAr : null });
      throw toJobError(e) ?? e;
    }
    if (scope.hash !== a.scope_hash) {
      const msg = 'تغيّر نطاق المصادر منذ طلب التوليد (حُذف مصدر أو تغيّرت نسخة)؛ لم يُكمَل التوليد. اطلب كتابًا جديدًا.';
      markRemaining(ctx, a.id, 'failed', msg);
      finalizeSectioned(ctx, a.id, { jobStatus: 'failed', jobError: msg });
      throw new JobError('OUT_OF_SCOPE', msg, { retryable: false });
    }
    const sections = sectionRows(ctx, a.id);
    const total = sections.length;
    let done = sections.filter((s) => s.status === 'complete' || s.status === 'abstained').length;
    run.progress({ stage: 'sections', done, total, unit: 'sections' });
    const only = params.only_sections ? new Set(params.only_sections) : null;
    for (const s of sections) {
      if (s.status === 'complete' || s.status === 'abstained' || s.status === 'failed') continue;
      if (only && !only.has(s.section_key)) continue; // not requested in this run: stays pending
      try {
        await run.checkpoint(`section:${s.section_key}`, async () => {
          // a finished section is never generated twice (crash after commit, before the checkpoint)
          const now = ctx.db.get<{ status: string }>('SELECT status FROM artifact_section WHERE artifact_id = ? AND section_key = ?', [a.id, s.section_key]);
          if (now?.status === 'complete' || now?.status === 'abstained') return { status: now.status };
          return generateSection(ctx, a, params, s, scope, run, hooks);
        });
      } catch (e) {
        // the interrupted section is reset: never published half-finished (AC-25)
        ctx.db.run(`UPDATE artifact_section SET status = 'pending', updated_at = ? WHERE artifact_id = ? AND section_key = ? AND status = 'generating'`, [ctx.clock.now(), a.id, s.section_key]);
        const fatal = toJobError(e);
        if (fatal) {
          markRemaining(ctx, a.id, 'failed', fatal.messageAr);
          finalizeSectioned(ctx, a.id, { jobStatus: 'failed', jobError: fatal.messageAr });
          throw fatal;
        }
        const provider = providerFailure(e);
        if (provider && !provider.retryable && !SECTION_LEVEL_PROVIDER_ERRORS.has(provider.kind)) {
          // the key / permission / model id / request shape: every section would fail the same way → stop now
          const msg = (e as { messageAr: string }).messageAr;
          markRemaining(ctx, a.id, 'failed', msg);
          finalizeSectioned(ctx, a.id, { jobStatus: 'failed', jobError: msg });
          throw new JobError('AI_PROVIDER_ERROR', msg, { retryable: false });
        }
        if ((isAppError(e) && e.code === 'SCHEMA_REJECTED') || (provider && !provider.retryable)) {
          // this section only (schema rejected after the one repair, refusal, truncation, too large): recorded as
          // failed with its specific reason, the others continue. A non-retryable failure is never asked again
          // by a job retry (it would only bill the same refusal again); «resume» lets the owner try it explicitly.
          setSection(ctx, a.id, s.section_key, 'failed', 0, { reason_ar: (e as { messageAr: string }).messageAr });
        } else {
          const lastAttempt = run.attempt >= 3;
          if (lastAttempt && !run.signal.aborted) {
            setSection(ctx, a.id, s.section_key, 'failed', 0, { reason_ar: isAppError(e) ? e.messageAr : 'تعذر توليد هذا القسم بعد عدة محاولات.' });
            continue;
          }
          throw e; // transient (provider error / timeout / cancel): the job retries and resumes from checkpoints
        }
      }
      done++;
      run.progress({ stage: 'sections', done, total, unit: 'sections' });
    }
    const status = finalizeSectioned(ctx, a.id, { jobStatus: 'completed', jobError: null });
    return { artifact_id: a.id, status };
  };
}

function setSection(ctx: AppContext, artifactId: string, key: string, status: StudyBookSectionView['status'], blocks: number, detail: Record<string, unknown> | null): void {
  ctx.db.run('UPDATE artifact_section SET status = ?, block_count = ?, detail_json = ?, updated_at = ? WHERE artifact_id = ? AND section_key = ?', [
    status,
    blocks,
    detail ? toJson(detail) : null,
    ctx.clock.now(),
    artifactId,
    key,
  ]);
}

function markRemaining(ctx: AppContext, artifactId: string, status: 'failed', reason: string): void {
  ctx.db.run(`UPDATE artifact_section SET status = ?, detail_json = ?, updated_at = ? WHERE artifact_id = ? AND status IN ('pending','generating')`, [
    status,
    toJson({ reason_ar: reason }),
    ctx.clock.now(),
    artifactId,
  ]);
}

async function generateSection(
  ctx: AppContext,
  a: ArtifactRow,
  params: SectionedParams,
  s: SectionRow,
  scope: ScopeReport,
  run: JobRun<SectionJobInput>,
  hooks: StudybookHooks,
): Promise<{ status: string; blocks: number }> {
  ctx.db.run(`UPDATE artifact_section SET status = 'generating', attempts = attempts + 1, updated_at = ? WHERE artifact_id = ? AND section_key = ?`, [ctx.clock.now(), a.id, s.section_key]);
  const regionIds = fromJson<string[]>(s.region_ids_json, []) ?? [];
  const regions = regionIds.length
    ? ctx.db.all<{ id: string; kind: string; text: string | null; page_id: string | null; page_index: number; printed_label: string | null; page_kind: PlanRegion['page_kind'] }>(
        `SELECT r.id, r.kind, r.text, r.page_id, p.page_index, p.printed_label, p.kind AS page_kind FROM source_region r JOIN source_page p ON p.id = r.page_id WHERE r.id IN (${regionIds.map(() => '?').join(',')})`,
        regionIds,
      )
    : [];
  const byId = new Map(regions.map((r) => [r.id, r]));
  const ordered = regionIds.map((id) => byId.get(id)).filter((r): r is NonNullable<typeof r> => !!r);
  if (ordered.length !== regionIds.length) {
    // the source was re-processed since planning: the planned regions no longer exist
    setSection(ctx, a.id, s.section_key, 'failed', 0, { reason_ar: 'تغيّرت مناطق هذا القسم في المصدر (أُعيدت معالجة الصفحة)؛ أعد توليد الكتاب.' });
    return { status: 'failed', blocks: 0 };
  }

  // evidence = the section's own regions (whole text, never top-k); figures are explained through their captions
  const evIds: string[] = [];
  const regionEvidence = new Map<string, string>();
  for (const r of ordered) {
    if (!r.text?.trim()) continue;
    try {
      const ev = fromRegion(ctx, r.id);
      evIds.push(ev.id);
      regionEvidence.set(r.id, ev.id);
    } catch {
      // not citable (rejected / generated) — the region is listed without evidence
    }
  }
  // references in the scope may support the section (lecture_plus_references); keyword candidates only from other sources
  if (params.mode === 'study_book' && scope.sourceIds.length > 1) {
    const q = [s.title ?? '', ...ordered.slice(0, 3).map((r) => (r.text ?? '').slice(0, 300))].join(' ');
    const rr = retrieve(ctx, { scope, query: q, k: 4, purpose: 'lecture_explanation' });
    for (const c of rr.candidates) {
      if (c.source_id === params.source_id) continue;
      for (const rid of c.region_ids.slice(0, 3)) {
        try {
          evIds.push(fromRegion(ctx, rid).id);
        } catch {
          /* not citable */
        }
      }
    }
  }
  const pack = buildEvidencePack(ctx, scope, evIds, { maxItems: 60 });
  if (pack.forModel.length === 0) {
    setSection(ctx, a.id, s.section_key, 'abstained', 0, { reason_ar: 'لا يحتوي هذا القسم نصًا مقروءًا يمكن الاستناد إليه.' });
    return { status: 'abstained', blocks: 0 };
  }
  const aliasOfEvidence = new Map(Object.entries(pack.aliasMap).map(([alias, id]) => [id, alias]));
  const regionAliases: Record<string, string> = {};
  const blocks: UntrustedBlock[] = [];
  ordered.forEach((r, i) => {
    const ra = `R${i + 1}`;
    regionAliases[ra] = r.id;
    const ev = regionEvidence.get(r.id);
    const ea = ev ? aliasOfEvidence.get(ev) : undefined;
    const loc = pageLabel({ page_index: r.page_index, printed_label: r.printed_label, kind: r.page_kind });
    if (ea) {
      const view = pack.forModel.find((f) => f.alias === ea)!;
      blocks.push({ label: `evidence ${ea} = region ${ra} (${r.kind}, ${loc})`, text: `[${ea}] [${ra}]\n${view.quote}` });
    } else {
      blocks.push({ label: `region ${ra} (${r.kind}, ${loc}) — no citable text`, text: `[${ra}] ${r.kind === 'figure' ? '(figure: explain it only through its caption / text evidence)' : '(no citable text)'}` });
    }
  });
  for (const f of pack.forModel) {
    if ([...regionEvidence.values()].some((id) => pack.aliasMap[f.alias] === id)) continue;
    blocks.push({ label: `evidence ${f.alias} — ${f.source_label} (supporting reference)`, text: `[${f.alias}]\n${f.quote}` });
  }
  const packed: PackedEvidence = {
    pack: { aliasMap: pack.aliasMap, regionAliases, views: pack.views } satisfies PackContext,
    candidates: [],
    blocks,
    versionIds: [...new Set(pack.views.map((v) => v.version_id))],
  };
  const isBook = params.mode === 'study_book';
  // the section title comes from the document (a heading region) — untrusted DATA: it is shown to the model only
  // inside a delimited block, never inside the trusted task text (AC-29)
  if (s.title) blocks.unshift({ label: isBook ? 'SECTION TITLE (from the source document)' : 'PAGES (labels of the pages summarized)', text: s.title });
  const taskText = isBook
    ? [
        `Write the MedLevo Study Book section titled in the SECTION TITLE block for the regions R1…R${ordered.length} (in their original order).`,
        'Start with ONE "heading" block (the section title in Arabic, keeping the English term). Then, for each region in order, write the blocks that explain it and set "explains_regions" to the R-aliases each block explains.',
        'Use "term" blocks for key terms, and the optional blocks allowed by the rules. Do not skip a region that has evidence; a region without citable text is mentioned only through what the evidence says.',
      ].join('\n')
    : [
        'Summarize the pages listed in the PAGES block (evidence excerpts in order).',
        SUMMARY_INSTRUCTIONS[params.summary_type ?? 'quick'],
        'Keep every negation, condition and exception that changes meaning. Set "explains_regions" to the R-aliases each block covers.',
      ].join('\n');
  const { content, model } = await callModel(ctx, scope, params.rules, packed, {
    task: isBook ? 'study_book' : 'summarize',
    style: 'detailed',
    taskText,
    ownerInstruction: params.instruction ?? null,
    terms: termsForTexts(ctx, ordered.map((r) => r.text ?? '')),
    jobId: run.id,
    signal: run.signal,
    maxOutputTokens: 9000,
    timeoutMs: 600_000,
  });
  if (run.signal.aborted) throw run.signal.reason;
  if (content.abstain && content.blocks.length === 0) {
    setSection(ctx, a.id, s.section_key, 'abstained', 0, { reason_ar: shorten(stripPseudoCitations(content.abstain.detail || '') || 'لم تكفِ الأدلة لهذا القسم.', 400) });
    return { status: 'abstained', blocks: 0 };
  }
  const processed = await processGenerated(ctx, content, {
    sectionKey: s.section_key,
    sectionTitle: s.title,
    scope,
    rules: params.rules,
    style: 'detailed',
    pack: packed.pack,
    defaultRegionIds: regionIds,
    ordBase: s.ord * 1000,
    jobId: run.id,
    signal: run.signal,
  });
  await hooks.beforeSectionPublish?.({ artifactId: a.id, sectionKey: s.section_key, attempt: run.attempt });
  if (run.signal.aborted) throw run.signal.reason;
  const status = processed.blocks.length > 0 && processed.keptMedical > 0 ? 'complete' : 'abstained';
  ctx.db.tx(() => {
    writeBlocks(ctx, a.id, s.section_key, status === 'complete' ? processed.blocks : []);
    setSection(ctx, a.id, s.section_key, status, status === 'complete' ? processed.blocks.length : 0, {
      removed: processed.removed,
      dropped_headings: processed.droppedHeadings,
      coverage_note: content.coverage_note ? stripPseudoCitations(content.coverage_note) || null : null,
      model,
      reason_ar: status === 'abstained' ? 'لم تجتز أي جملة طبية في هذا القسم التحقق من الأدلة؛ لم يُنشر.' : null,
    });
    if (status === 'complete') recordBlockDependencies(ctx, a.id, processed.blocks, [params.version_id]);
    ctx.db.run('UPDATE artifact SET model = ?, updated_at = ? WHERE id = ?', [model, ctx.clock.now(), a.id]);
    indexArtifact(ctx, a.id);
  });
  return { status, blocks: status === 'complete' ? processed.blocks.length : 0 };
}

/** Final status + coverage + removed list; supersedes older versions and reports re-anchoring. Returns the status. */
export function finalizeSectioned(ctx: AppContext, artifactId: string, o: { jobStatus: string; jobError: string | null }): string {
  const a = requireArtifact(ctx, artifactId);
  const sections = sectionRows(ctx, artifactId);
  const complete = sections.filter((s) => s.status === 'complete');
  const failed = sections.filter((s) => s.status === 'failed' || s.status === 'pending' || s.status === 'generating');
  const params = fromJson<SectionedParams>(a.params_json);
  let status: StudyBookView['artifact']['status'];
  if (complete.length === 0) status = 'failed';
  else if (failed.length === 0) status = 'published';
  else status = 'partial';

  const removed: Array<{ text: string; reason_ar: string }> = [];
  const missing: string[] = [];
  const coveredPages = new Set<string>();
  for (const s of sections) {
    const d = fromJson<{ removed?: Array<{ text: string; reason_ar: string }>; dropped_headings?: string[]; reason_ar?: string | null; coverage_note?: string | null }>(s.detail_json) ?? {};
    removed.push(...(d.removed ?? []));
    if (s.status === 'complete') {
      for (const p of fromJson<string[]>(s.page_ids_json, []) ?? []) coveredPages.add(p);
      for (const h of d.dropped_headings ?? []) missing.push(`«${s.title ?? ''}»: لم تذكر المصادر ${h}`);
    } else {
      missing.push(`القسم «${s.title ?? s.section_key}»: ${s.status === 'abstained' ? (d.reason_ar ?? 'لا أدلة كافية') : (d.reason_ar ?? o.jobError ?? 'لم يكتمل توليده')}`);
    }
  }
  const prevCoverage = fromJson<Record<string, unknown>>(a.coverage_json) ?? {};
  const prevMissing = Array.isArray(prevCoverage.missing_ar) ? (prevCoverage.missing_ar as string[]).filter((m) => !m.startsWith('القسم «') && !m.includes(': لم تذكر المصادر')) : [];
  const pagesTotal = typeof prevCoverage.pages_total === 'number' ? prevCoverage.pages_total : coveredPages.size;
  const coverage: Record<string, unknown> = {
    pages_total: pagesTotal,
    pages_covered: coveredPages.size,
    sections_total: sections.length,
    sections_covered: complete.length,
  };
  if (params?.mode === 'study_book') {
    // pages of the version that no section covers (unreadable / no text) are listed, never hidden
    const pages = versionPages(ctx, params.version_id);
    const planned = new Set(sections.flatMap((s) => fromJson<string[]>(s.page_ids_json, []) ?? []));
    const uncovered = pages.filter((p) => !planned.has(p.id));
    if (uncovered.length) prevMissing.push(`صفحات بلا نص معالَج لم يشملها الكتاب: ${uncovered.map(pageLabel).join('، ')}`);
  }
  const allMissing = [...new Set([...prevMissing, ...missing])];
  if (allMissing.length) coverage.missing_ar = allMissing;
  const now = ctx.clock.now();
  ctx.db.tx(() => {
    ctx.db.run(`UPDATE artifact SET status = ?, coverage_json = ?, removed_json = ?, published_at = CASE WHEN ? IN ('published','partial') THEN ? ELSE published_at END, updated_at = ? WHERE id = ?`, [
      status,
      toJson(coverage),
      toJson(removed),
      status,
      now,
      now,
      artifactId,
    ]);
    if (status === 'published' || status === 'partial') {
      if (status === 'published') {
        // older non-frozen published versions of the lineage are superseded (frozen ones stay as pinned)
        ctx.db.run(`UPDATE artifact SET status = 'superseded', updated_at = ? WHERE lineage_id = ? AND id <> ? AND version_no < ? AND is_frozen = 0 AND status IN ('published','partial')`, [
          now,
          a.lineage_id,
          a.id,
          a.version_no,
        ]);
      }
      if (a.kind === 'study_book') computeReanchor(ctx, artifactId);
    }
    indexArtifact(ctx, artifactId);
  });
  if (o.jobStatus === 'cancelled' && status !== 'failed') ctx.audit.record({ entityType: 'artifact', entityId: artifactId, action: 'generation_cancelled', summary: `أُلغي توليد «${a.title ?? ''}» بعد ${complete.length} من ${sections.length} أقسام.` });
  return status;
}

// ───────── re-anchoring (§25, AC-22) ─────────
function blockPlain(contentJson: string | null): string {
  try {
    return richTextToPlain(parseRichText(fromJson(contentJson)));
  } catch {
    return '';
  }
}

/**
 * Owner notes / annotations anchored to blocks of this lineage: matched or needs_reanchor.
 * A block key is hash(section, explained regions, kind, ordinal): when a regeneration writes fewer paragraphs about a
 * region, or reorders them, ANOTHER paragraph inherits the key. A key match therefore only counts when the paragraph
 * now holding it is still the paragraph the note was written on — its block in the anchored version, else the quote
 * the anchor kept (G6 / AC-22). Otherwise the note stays where it is, untouched, and is listed for re-anchoring.
 */
export function computeReanchor(ctx: AppContext, artifactId: string): ReanchorItem[] {
  const a = requireArtifact(ctx, artifactId);
  const blockText = new Map(
    ctx.db.all<{ block_key: string; content_json: string | null }>('SELECT block_key, content_json FROM content_block WHERE artifact_id = ?', [artifactId]).map((r) => [r.block_key, r.content_json] as const),
  );
  const keys = new Set(blockText.keys());
  /** the paragraph the anchor was written on: (text, is a prefix quote) — null when nothing is known */
  const anchoredText = (blockKey: string, version: number | null, anchorJson: string | null): { text: string; prefix: boolean } | null => {
    if (version !== null && version !== a.version_no) {
      const row = ctx.db.get<{ content_json: string | null }>(
        `SELECT cb.content_json FROM content_block cb JOIN artifact x ON x.id = cb.artifact_id WHERE x.lineage_id = ? AND x.version_no = ? AND cb.block_key = ? LIMIT 1`,
        [a.lineage_id, version, blockKey],
      );
      if (row) return { text: blockPlain(row.content_json), prefix: false };
    }
    if (version === a.version_no) return null; // written on this very version
    const quote = fromJson<{ quote?: { exact?: string } }>(anchorJson)?.quote?.exact;
    return quote ? { text: quote, prefix: true } : null;
  };
  const prefix = `${a.lineage_id}:`;
  const anns = ctx.db.all<{ id: string; target_id: string; anchor_json: string | null }>(
    `SELECT a.id, t.target_id, a.anchor_json FROM annotation_target t JOIN annotation a ON a.id = t.annotation_id
      WHERE t.target_type = 'artifact_block' AND substr(t.target_id, 1, ?) = ? AND a.deleted_at IS NULL`,
    [prefix.length, prefix],
  );
  const notes = ctx.db.all<{ id: string; anchor_target_key: string; anchor_json: string | null }>(
    `SELECT id, anchor_target_key, anchor_json FROM note WHERE substr(anchor_target_key, 1, ?) = ? AND deleted_at IS NULL`,
    [`artifact_block:${prefix}`.length, `artifact_block:${prefix}`],
  );
  const items: Array<{ kind: 'annotation' | 'note'; id: string; blockKey: string; prevVersion: number | null; anchorJson: string | null }> = [
    ...anns.map((x) => ({ kind: 'annotation' as const, id: x.id, blockKey: x.target_id.slice(prefix.length), prevVersion: fromJson<{ artifact_version?: number }>(x.anchor_json)?.artifact_version ?? null, anchorJson: x.anchor_json })),
    ...notes.map((x) => ({ kind: 'note' as const, id: x.id, blockKey: x.anchor_target_key.slice(`artifact_block:${prefix}`.length), prevVersion: fromJson<{ artifact_version?: number }>(x.anchor_json)?.artifact_version ?? null, anchorJson: x.anchor_json })),
  ];
  const now = ctx.clock.now();
  // sections of THIS version that are not finished (pending / failed / generating): their paragraphs may still
  // come; a note on one of them is not reported as needing re-anchoring until the section is decided
  const unfinished = new Set(
    ctx.db.all<{ section_key: string }>(`SELECT section_key FROM artifact_section WHERE artifact_id = ? AND status NOT IN ('complete','abstained')`, [artifactId]).map((r) => r.section_key),
  );
  const sectionOfBlock = (blockKey: string): string | null =>
    ctx.db.get<{ section_key: string | null }>(
      `SELECT cb.section_key FROM content_block cb JOIN artifact x ON x.id = cb.artifact_id WHERE x.lineage_id = ? AND cb.block_key = ? LIMIT 1`,
      [a.lineage_id, blockKey],
    )?.section_key ?? null;
  for (const it of items) {
    let status: 'matched' | 'needs_reanchor' = keys.has(it.blockKey) ? 'matched' : 'needs_reanchor';
    if (status === 'matched') {
      const then = anchoredText(it.blockKey, it.prevVersion, it.anchorJson);
      if (then && !samePassage(then.text, blockPlain(blockText.get(it.blockKey) ?? null), then.prefix)) status = 'needs_reanchor';
    }
    if (status === 'needs_reanchor' && unfinished.size) {
      const sec = sectionOfBlock(it.blockKey);
      if (sec && unfinished.has(sec)) continue;
    }
    if (status === 'matched') {
      // an earlier version's report said this paragraph was gone; it is back → that server-made item is closed
      ctx.db.run(
        `UPDATE review_queue_item SET status = 'dismissed', resolved_at = ?, resolution_json = ?
          WHERE kind = 'needs_reanchor' AND entity_type = ? AND entity_id = ? AND status = 'open'
            AND json_extract(details_json, '$.origin') = 'studybook' AND json_extract(details_json, '$.lineage_id') = ?`,
        [now, toJson({ by: 'server', reason_ar: `الفقرة نفسها موجودة في النسخة ${a.version_no} من كتاب الدراسة؛ بقيت الملاحظة مرتبطة بها ولم يتغير فيها شيء.` }), it.kind, it.id, a.lineage_id],
      );
    }
    ctx.db.run(
      `INSERT INTO artifact_reanchor (artifact_id, target_kind, target_id, block_key, previous_version_no, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT (artifact_id, target_kind, target_id) DO UPDATE SET block_key = excluded.block_key, previous_version_no = excluded.previous_version_no, status = excluded.status`,
      [artifactId, it.kind, it.id, it.blockKey, it.prevVersion, status, now],
    );
    if (status === 'needs_reanchor') {
      const open = ctx.db.get(`SELECT 1 AS x FROM review_queue_item WHERE kind = 'needs_reanchor' AND entity_type = ? AND entity_id = ? AND status = 'open'`, [it.kind, it.id]);
      if (!open) {
        ctx.db.run(
          `INSERT INTO review_queue_item (id, kind, entity_type, entity_id, source_id, reason, details_json, status, created_at) VALUES (?, 'needs_reanchor', ?, ?, ?, ?, ?, 'open', ?)`,
          [
            newId(now),
            it.kind,
            it.id,
            a.primary_source_id,
            keys.has(it.blockKey)
              ? `${it.kind === 'note' ? 'ملاحظة' : 'كتابة'} مرتبطة بفقرة من كتاب الدراسة تغيّر نصها في النسخة ${a.version_no} (فقرة أخرى في مكانها)؛ لم تُنقل إليها، وحُفظت كما هي وتحتاج إعادة ربط.`
              : `${it.kind === 'note' ? 'ملاحظة' : 'كتابة'} مرتبطة بفقرة من كتاب الدراسة لم تعد موجودة في النسخة ${a.version_no}؛ حُفظت كما هي وتحتاج إعادة ربط.`,
            toJson({ origin: 'studybook', lineage_id: a.lineage_id, block_key: it.blockKey, previous_version_no: it.prevVersion, new_version_no: a.version_no, artifact_id: a.id }),
            now,
          ],
        );
      }
    }
  }
  return reanchorItems(ctx, artifactId);
}

export { JOB_STATUS_LABELS_AR };
