// G7 — AC-30 «الاستعادة»: a backup brings back sources, books, ink, questions, links and sessions VERIFIABLY; an archive
// without a tested restore is not enough.
//
// Adversarial additions to test/data/backup-restore.test.ts (which restores through the library functions and compares
// a list of key tables):
//  * the backup and the restore run through the REAL command-line tools as separate processes (`src/cli/backup.ts`
//    while the server is up, `src/cli/restore-verify.ts <archive> --target <dir>`), checking their exit codes and report;
//  * EVERY table of the database is compared row by row after the restore — not a chosen list — and the only allowed
//    differences are the ones a restore makes on purpose (sessions revoked, a new sync epoch, the restore entry in the
//    history, the CLI's own backup record), each asserted precisely;
//  * the owner's view is compared through the read APIs the web app uses (library, sources, pages, ink on lecture pages
//    AND on a separate note page, notes, the reading position, questions with their keys and lecture links, cards with
//    their review log and schedule, an exam in progress with its answers, a finished exam's result, the Study Book,
//    Arabic keyword search, reading progress) — the restored server must answer exactly the same.
// The Study Book is generated by the real job with the TEST-ONLY scripted provider (no API key exists here).
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { ExamSessionView, QuestionListItem } from '@medlevo/shared';
import { openDb, type Db } from '../../src/db/db';
import { newId } from '../../src/lib/ids';
import { createTestApp, CSRF, OWNER, sessionCookie, type AuthHeaders, type TestApp } from '../helpers/app';
import { dataLibrary, pageAnchor, push, rt, writeOwnerData, type DataLib, type OwnerData } from '../data/helpers';
import { stateOf } from './g4-helpers';

const SERVER_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
let lib: DataLib;
let owner: OwnerData;
let work: string;
let archive: string;
let target: string;
let restored: TestApp;
let rh: AuthHeaders;
let inProgress: ExamSessionView;
let finished: ExamSessionView;
let notePageId: string;
let notePageInk: string;
let pageInkId: string;
let cardId: string;

function cli(script: string, args: string[]) {
  const r = spawnSync(process.execPath, ['--disable-warning=ExperimentalWarning', '--import', 'tsx', join(SERVER_DIR, 'src', 'cli', script), ...args], {
    cwd: SERVER_DIR,
    env: { ...process.env, INIT_CWD: SERVER_DIR, MEDLEVO_LOG_LEVEL: 'silent', ANTHROPIC_API_KEY: '' },
    encoding: 'utf8',
    timeout: 240_000,
  });
  return { status: r.status, out: `${r.stdout ?? ''}${r.stderr ?? ''}` };
}

beforeAll(async () => {
  lib = await dataLibrary();
  owner = await writeOwnerData(lib);
  const now = lib.t.ctx.clock.now();

  // ink on a separate handwritten note page that belongs to the lecture (§26)
  notePageId = newId();
  notePageInk = newId();
  pageInkId = newId();
  const stroke = (anchor: unknown, x: number) => ({
    kind: 'ink',
    tool: 'fountain',
    anchor,
    data: { v: 1, points: [[x, 0.4, 0, 0.4], [x + 0.05, 0.42, 16, 0.7], [x + 0.1, 0.45, 32, 0.5]], style: { tool: 'fountain', color: 'ink-black', width: 0.003 }, bbox: { x, y: 0.4, w: 0.1, h: 0.05 }, pressure_available: true, tilt_available: true },
    layer: 'ink',
    z: 1,
    locked: false,
  });
  const r1 = await push(lib, [
    { entity_type: 'note_page', entity_id: notePageId, op: 'upsert', payload: { source_id: lib.lecture.sourceId, after_page_index: 1, title: 'صفحة ملاحظاتي — Appendicitis', template: 'ruled', width: 595, height: 842, sort_order: 1 } },
    { entity_type: 'annotation', entity_id: notePageInk, op: 'append', payload: stroke({ type: 'note_page', note_page_id: notePageId, space: 'page_norm' }, 0.1) },
    { entity_type: 'annotation', entity_id: pageInkId, op: 'append', payload: stroke(pageAnchor(lib, 2), 0.5) },
  ]);
  for (const r of r1) expect(r.result, JSON.stringify(r)).toBe('applied');

  // cards + reviews through sync (the review state cache is derived by the server)
  cardId = newId();
  const r2 = await push(lib, [
    { entity_type: 'flashcard', entity_id: cardId, op: 'upsert', payload: { kind: 'basic', front: rt('ما الفحص الأول عند امرأة في سن الإنجاب؟'), back: rt('Pregnancy test (β-hCG)'), source_id: lib.lecture.sourceId } },
    { entity_type: 'review_event', entity_id: newId(), op: 'append', payload: { card_id: cardId, rating: 3, reviewed_at: now - 86_400_000, duration_ms: 5000 } },
    { entity_type: 'review_event', entity_id: newId(), op: 'append', payload: { card_id: cardId, rating: 2, reviewed_at: now - 3_600_000, duration_ms: 7000 } },
  ]);
  for (const r of r2) expect(r.result, JSON.stringify(r)).toBe('applied');

  // an exam in progress (two answers on the server) and a finished one
  const qsrc = lib.questions.sourceId;
  const mk = async (seed: string): Promise<ExamSessionView> => {
    const res = await lib.t.app.inject({ method: 'POST', url: '/api/exams', headers: lib.h, payload: { title: '', mode: 'exam', count: 3, source_ids: [qsrc], seed } });
    expect(res.statusCode, res.body).toBe(200);
    return (res.json() as { session: ExamSessionView }).session;
  };
  const answers = (s: ExamSessionView, n: number) =>
    Object.fromEntries(s.items.slice(0, n).map((it) => [String(it.index), { attempt_id: newId(), selected_option_ids: [it.options[0]!.id], confidence: 'unsure', at: now, time_ms: 9000, hints_used: 0, solution_viewed_before_answer: false, submitted: false }]));
  inProgress = await mk('g7-ac30-progress');
  finished = await mk('g7-ac30-finished');
  const r3 = await push(lib, [
    { entity_type: 'exam_attempt', entity_id: inProgress.attempt.id, op: 'upsert', payload: stateOf(inProgress, { status: 'in_progress', answers: answers(inProgress, 2) as never, elapsed_ms: 60_000, current_index: 2 }) },
    { entity_type: 'exam_attempt', entity_id: finished.attempt.id, op: 'upsert', payload: stateOf(finished, { status: 'completed', answers: answers(finished, 3) as never, elapsed_ms: 90_000, finished_at: now } as never) },
  ]);
  for (const r of r3) expect(['applied', 'merged'], JSON.stringify(r)).toContain(r.result);

  // an owner preference and reading progress
  expect((await lib.t.app.inject({ method: 'PATCH', url: '/api/settings', headers: lib.h, payload: { explanation_level: 'exam_focus' } })).statusCode).toBe(200);
  expect((await lib.t.app.inject({ method: 'POST', url: '/api/annotations/progress', headers: lib.h, payload: { source_id: lib.lecture.sourceId, version_id: lib.lecture.versionId, page_indexes: [0, 1] } })).statusCode).toBe(200);

  work = mkdtempSync(join(tmpdir(), 'medlevo-g7-ac30-'));
  target = join(work, 'restored');
}, 300_000);

afterAll(async () => {
  await restored?.close().catch(() => undefined);
  await lib?.t.close();
  if (work) rmSync(work, { recursive: true, force: true });
});

const ALL_TABLES = (db: Db) =>
  db
    .all<{ name: string }>("SELECT name FROM sqlite_schema WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND sql NOT LIKE 'CREATE VIRTUAL TABLE%' ORDER BY name")
    .map((r) => r.name)
    .filter((n) => !/_fts_(data|idx|docsize|config|content)$/.test(n));

describe('AC-30 through the real command-line tools', () => {
  it('`backup` (a separate process, server running) writes ONE archive + .sha256; the archive matches its checksum', () => {
    const out = join(work, 'archives');
    const r = cli('backup.ts', ['--data-dir', lib.t.dataDir, '--out', out]);
    expect([0, 3], r.out).toContain(r.status);
    const files = readdirSync(out);
    const tgz = files.filter((f) => f.endsWith('.tar.gz'));
    expect(tgz, files.join(', ')).toHaveLength(1);
    archive = join(out, tgz[0]!);
    const side = readFileSync(`${archive}.sha256`, 'utf8');
    const sum = spawnSync('sha256sum', ['-c', `${tgz[0]}.sha256`], { cwd: out, encoding: 'utf8' });
    expect(sum.status, `${side}\n${sum.stdout}${sum.stderr}`).toBe(0);
  }, 300_000);

  it('`restore:verify <archive> --target <empty dir>` passes every check (boot included) and restores', () => {
    const r = cli('restore-verify.ts', [archive, '--target', target, '--json', join(work, 'report.json')]);
    expect(r.status, r.out).toBe(0);
    expect(r.out).toContain('RESULT: PASS');
    const report = JSON.parse(readFileSync(join(work, 'report.json'), 'utf8')) as { ok: boolean; checks: Array<{ name: string; ok: boolean }> };
    expect(report.ok).toBe(true);
    expect(report.checks.filter((c) => !c.ok)).toEqual([]);
    expect(report.checks.map((c) => c.name)).toEqual(expect.arrayContaining(['file_hashes', 'integrity_check', 'foreign_keys', 'fts', 'links', 'sessions', 'learning', 'boot']));
    expect(existsSync(join(target, 'medlevo.sqlite'))).toBe(true);
    // a second restore into the same (now non-empty) directory is refused: a restore never overwrites
    const again = cli('restore-verify.ts', [archive, '--target', target]);
    expect(again.status, again.out).toBe(2);
  }, 300_000);

  it('EVERY table comes back row for row; the only differences are the ones a restore makes on purpose', () => {
    const rdb = openDb(join(target, 'medlevo.sqlite'));
    try {
      const live = lib.t.ctx.db;
      const tables = ALL_TABLES(live);
      expect(ALL_TABLES(rdb)).toEqual(tables);
      const differing: string[] = [];
      for (const t of tables) {
        const a = live.all(`SELECT * FROM "${t}" ORDER BY rowid`);
        const b = rdb.all(`SELECT * FROM "${t}" ORDER BY rowid`);
        if (JSON.stringify(a) !== JSON.stringify(b)) differing.push(t);
      }
      // documented, deliberate differences (docs/BACKUP_RESTORE.md §3): every session revoked, a new current sync epoch,
      // the restore recorded in the history. Nothing else — not one row of the owner's data — differs.
      expect(differing.sort()).toEqual(['auth_session', 'change_log', 'data_server_epoch']);
      expect(tables.length).toBeGreaterThan(60);
      expect(rdb.get<{ n: number }>('SELECT COUNT(*) AS n FROM auth_session WHERE revoked_at IS NULL')!.n).toBe(0);
      const liveLog = live.all<{ id: string }>('SELECT id FROM change_log ORDER BY rowid').map((r) => r.id);
      const restoredLog = rdb.all<{ id: string; action: string }>('SELECT id, action FROM change_log ORDER BY rowid');
      expect(restoredLog.filter((r) => r.action !== 'restore').map((r) => r.id)).toEqual(liveLog.filter((id) => restoredLog.some((r) => r.id === id)));
      expect(restoredLog.filter((r) => r.action === 'restore')).toHaveLength(1);
      expect(rdb.get<{ n: number }>('SELECT COUNT(*) AS n FROM data_server_epoch WHERE is_current = 1 AND reason = ?', ['restore'])!.n).toBe(1);
    } finally {
      rdb.close();
    }
  });
});

describe('AC-30 the restored server shows the owner exactly what the live one shows', () => {
  beforeAll(async () => {
    restored = await createTestApp({ env: { MEDLEVO_DATA_DIR: target } });
    // the old session is revoked: devices sign in again
    expect((await restored.app.inject({ method: 'GET', url: '/api/library/tree', headers: { cookie: lib.h.cookie } })).statusCode).toBe(401);
    const login = await restored.app.inject({ method: 'POST', url: '/api/auth/login', headers: CSRF, payload: { username: OWNER.username, password: OWNER.password } });
    expect(login.statusCode, login.body).toBe(200);
    rh = { cookie: sessionCookie(login), ...CSRF };
  }, 120_000);

  /** volatile parts that legitimately differ between two servers: signed media URLs (new server secret) */
  const stable = (v: unknown): unknown => JSON.parse(JSON.stringify(v).replace(/"(media_url|url|download_url|token)":"[^"]*"/g, '"$1":"<signed>"').replace(/"media_expires_at":\d+/g, '"media_expires_at":0'));

  async function same(url: string): Promise<unknown> {
    const a = await lib.t.app.inject({ method: 'GET', url, headers: lib.h });
    const b = await restored.app.inject({ method: 'GET', url, headers: rh });
    expect(a.statusCode, `${url} live: ${a.body.slice(0, 300)}`).toBe(200);
    expect(b.statusCode, `${url} restored: ${b.body.slice(0, 300)}`).toBe(200);
    expect(stable(b.json()), url).toEqual(stable(a.json()));
    return b.json();
  }

  it('library, sources, pages and both files (bytes identical)', async () => {
    await same('/api/library/tree');
    for (const s of [lib.lecture.sourceId, lib.questions.sourceId]) {
      const d = (await same(`/api/sources/${s}`)) as { active_version_id: string };
      await same(`/api/sources/${s}/versions/${d.active_version_id}/pages`);
    }
    const fid = lib.t.ctx.db.get<{ file_id: string }>('SELECT file_id FROM source_version WHERE id = ?', [lib.lecture.versionId])!.file_id;
    const a = await lib.t.app.inject({ method: 'GET', url: `/api/files/${fid}`, headers: lib.h });
    const b = await restored.app.inject({ method: 'GET', url: `/api/files/${fid}`, headers: rh });
    expect(b.statusCode).toBe(200);
    expect(Buffer.compare(a.rawPayload, b.rawPayload)).toBe(0);
  });

  it('ink (lecture pages AND the handwritten note page), highlights, notes, the reading position and progress', async () => {
    const ann = (await same(`/api/annotations/source/${lib.lecture.sourceId}?version_id=${lib.lecture.versionId}`)) as { annotations: Array<{ id: string; kind: string }>; note_pages: Array<{ id: string }>; notes: Array<{ id: string }> };
    expect(ann.annotations.filter((a) => a.kind === 'ink').map((a) => a.id).sort()).toEqual([owner.inkId, pageInkId, notePageInk].sort());
    expect(ann.annotations.map((a) => a.id)).toContain(owner.highlightId);
    expect(ann.note_pages.map((p) => p.id)).toEqual([notePageId]);
    expect(ann.notes.map((n) => n.id)).toEqual([owner.noteId]);
    await same(`/api/annotations/notes?source_id=${lib.lecture.sourceId}`);
    const s = (await same(`/api/annotations/sessions/latest?source_id=${lib.lecture.sourceId}`)) as { session: { id: string; location: { page_index: number; zoom: number } } };
    expect(s.session).toMatchObject({ id: owner.sessionId, location: { page_index: 1, zoom: 1.25 } });
    await same(`/api/annotations/progress/${lib.lecture.sourceId}`);
  });

  it('questions with keys, their lecture links and the Arabic/English keyword search', async () => {
    const list = (await same('/api/questions?limit=200')) as { items: QuestionListItem[] };
    expect(list.items.length).toBeGreaterThan(3);
    for (const q of list.items.slice(0, 6)) await same(`/api/questions/${q.id}`);
    const lq = (await same(`/api/questions/for-lecture/${lib.lecture.sourceId}`)) as { items: unknown[] };
    expect(lq.items.length).toBeGreaterThan(0);
    await same(`/api/search?q=${encodeURIComponent('الالم')}`);
    await same(`/api/search?q=${encodeURIComponent('McBurney')}`);
  });

  it('cards with their review log and the schedule derived from it; exams in progress (answers) and finished (result)', async () => {
    const c = (await same(`/api/learning/cards/${cardId}`)) as { events: unknown[]; card: { review_state: { reps: number } } };
    expect(c.events).toHaveLength(2);
    expect(c.card.review_state.reps).toBe(2);
    for (const id of owner.cardIds) await same(`/api/learning/cards/${id}`);
    await same('/api/exams/attempts');
    const p = (await same(`/api/exams/attempts/${inProgress.attempt.id}`)) as ExamSessionView;
    expect(p.attempt.status).toBe('in_progress');
    expect(Object.keys(p.attempt.answers)).toHaveLength(2);
    expect(p.attempt.current_index).toBe(2);
    const r = (await same(`/api/exams/attempts/${finished.attempt.id}/result`)) as { answered: number; missing_on_server: number };
    expect(r).toMatchObject({ answered: 3, missing_on_server: 0 });
  });

  it('the Study Book with its blocks, claims and citations; the owner settings', async () => {
    const book = (await same(`/api/studybook/books/${owner.book!.artifact.id}`)) as { artifact: { status: string; blocks: unknown[]; claims: Record<string, { citations: unknown[] }> } };
    expect(book.artifact.status).toBe('published');
    expect(book.artifact.blocks.length).toBeGreaterThan(0);
    expect(Object.values(book.artifact.claims).some((c) => c.citations.length > 0)).toBe(true);
    const s = (await same('/api/settings')) as { settings: { explanation_level: string } };
    expect(s.settings.explanation_level).toBe('exam_focus');
  });

  it('the restored server keeps working: a write after the restore is accepted under the new epoch', async () => {
    const pull = (await restored.app.inject({ method: 'GET', url: '/api/sync/pull?since=0&limit=1', headers: rh })).json() as { server_epoch: string };
    const res = await restored.app.inject({
      method: 'POST',
      url: '/api/sync/push',
      headers: rh,
      payload: { server_epoch: pull.server_epoch, ops: [{ op_id: newId(), device_id: 'G7_AFTER_RESTORE', entity_type: 'note', entity_id: newId(), op: 'upsert', payload: { title: null, body: rt('بعد الاستعادة'), anchor: pageAnchor(lib, 0), origin: 'owner' } }] },
    });
    expect(res.statusCode, res.body).toBe(200);
    expect(res.json().results[0].result).toBe('applied');
  });
});
